// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.databricks.AccountSettingV2Args;
import com.pulumi.databricks.Utilities;
import com.pulumi.databricks.inputs.AccountSettingV2State;
import com.pulumi.databricks.outputs.AccountSettingV2AibiDashboardEmbeddingAccessPolicy;
import com.pulumi.databricks.outputs.AccountSettingV2AibiDashboardEmbeddingApprovedDomains;
import com.pulumi.databricks.outputs.AccountSettingV2AutomaticClusterUpdateWorkspace;
import com.pulumi.databricks.outputs.AccountSettingV2BooleanVal;
import com.pulumi.databricks.outputs.AccountSettingV2EffectiveAibiDashboardEmbeddingAccessPolicy;
import com.pulumi.databricks.outputs.AccountSettingV2EffectiveAibiDashboardEmbeddingApprovedDomains;
import com.pulumi.databricks.outputs.AccountSettingV2EffectiveAutomaticClusterUpdateWorkspace;
import com.pulumi.databricks.outputs.AccountSettingV2EffectiveBooleanVal;
import com.pulumi.databricks.outputs.AccountSettingV2EffectiveIntegerVal;
import com.pulumi.databricks.outputs.AccountSettingV2EffectivePersonalCompute;
import com.pulumi.databricks.outputs.AccountSettingV2EffectiveRestrictWorkspaceAdmins;
import com.pulumi.databricks.outputs.AccountSettingV2EffectiveStringVal;
import com.pulumi.databricks.outputs.AccountSettingV2IntegerVal;
import com.pulumi.databricks.outputs.AccountSettingV2PersonalCompute;
import com.pulumi.databricks.outputs.AccountSettingV2RestrictWorkspaceAdmins;
import com.pulumi.databricks.outputs.AccountSettingV2StringVal;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * [![Public Beta](https://img.shields.io/badge/Release_Stage-Public_Beta-orange)](https://docs.databricks.com/aws/en/release-notes/release-types)
 * 
 * Setting is a configurable value or control that determines how a feature or behavior works within the databricks platform.
 * 
 * [//]: # (todo: add public link to metadata api after production doc link available)
 * See settings-metadata api for list of settings that can be modified using this resource.
 * 
 * ## Example Usage
 * 
 * Getting an account level setting:
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.databricks.AccountSettingV2;
 * import com.pulumi.databricks.AccountSettingV2Args;
 * import com.pulumi.databricks.inputs.AccountSettingV2BooleanValArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var this_ = new AccountSettingV2("this", AccountSettingV2Args.builder()
 *             .name("llm_proxy_partner_powered")
 *             .booleanVal(AccountSettingV2BooleanValArgs.builder()
 *                 .value(false)
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Import
 * 
 * As of Pulumi v1.5, resources can be imported through configuration.
 * 
 * hcl
 * 
 * import {
 * 
 *   id = &#34;name&#34;
 * 
 *   to = databricks_account_setting_v2.this
 * 
 * }
 * 
 * If you are using an older version of Pulumi, import the resource using the `pulumi import` command as follows:
 * 
 * ```sh
 * $ pulumi import databricks:index/accountSettingV2:AccountSettingV2 this &#34;name&#34;
 * ```
 * 
 */
@ResourceType(type="databricks:index/accountSettingV2:AccountSettingV2")
public class AccountSettingV2 extends com.pulumi.resources.CustomResource {
    /**
     * Setting value for aibiDashboardEmbeddingAccessPolicy setting. This is the setting value set by consumers, check effectiveAibiDashboardEmbeddingAccessPolicy for final setting value
     * 
     */
    @Export(name="aibiDashboardEmbeddingAccessPolicy", refs={AccountSettingV2AibiDashboardEmbeddingAccessPolicy.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2AibiDashboardEmbeddingAccessPolicy> aibiDashboardEmbeddingAccessPolicy;

    /**
     * @return Setting value for aibiDashboardEmbeddingAccessPolicy setting. This is the setting value set by consumers, check effectiveAibiDashboardEmbeddingAccessPolicy for final setting value
     * 
     */
    public Output<Optional<AccountSettingV2AibiDashboardEmbeddingAccessPolicy>> aibiDashboardEmbeddingAccessPolicy() {
        return Codegen.optional(this.aibiDashboardEmbeddingAccessPolicy);
    }
    /**
     * Setting value for aibiDashboardEmbeddingApprovedDomains setting. This is the setting value set by consumers, check effectiveAibiDashboardEmbeddingApprovedDomains for final setting value
     * 
     */
    @Export(name="aibiDashboardEmbeddingApprovedDomains", refs={AccountSettingV2AibiDashboardEmbeddingApprovedDomains.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2AibiDashboardEmbeddingApprovedDomains> aibiDashboardEmbeddingApprovedDomains;

    /**
     * @return Setting value for aibiDashboardEmbeddingApprovedDomains setting. This is the setting value set by consumers, check effectiveAibiDashboardEmbeddingApprovedDomains for final setting value
     * 
     */
    public Output<Optional<AccountSettingV2AibiDashboardEmbeddingApprovedDomains>> aibiDashboardEmbeddingApprovedDomains() {
        return Codegen.optional(this.aibiDashboardEmbeddingApprovedDomains);
    }
    /**
     * Setting value for automaticClusterUpdateWorkspace setting. This is the setting value set by consumers, check effectiveAutomaticClusterUpdateWorkspace for final setting value
     * 
     */
    @Export(name="automaticClusterUpdateWorkspace", refs={AccountSettingV2AutomaticClusterUpdateWorkspace.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2AutomaticClusterUpdateWorkspace> automaticClusterUpdateWorkspace;

    /**
     * @return Setting value for automaticClusterUpdateWorkspace setting. This is the setting value set by consumers, check effectiveAutomaticClusterUpdateWorkspace for final setting value
     * 
     */
    public Output<Optional<AccountSettingV2AutomaticClusterUpdateWorkspace>> automaticClusterUpdateWorkspace() {
        return Codegen.optional(this.automaticClusterUpdateWorkspace);
    }
    /**
     * Setting value for boolean type setting. This is the setting value set by consumers, check effectiveBooleanVal for final setting value
     * 
     */
    @Export(name="booleanVal", refs={AccountSettingV2BooleanVal.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2BooleanVal> booleanVal;

    /**
     * @return Setting value for boolean type setting. This is the setting value set by consumers, check effectiveBooleanVal for final setting value
     * 
     */
    public Output<Optional<AccountSettingV2BooleanVal>> booleanVal() {
        return Codegen.optional(this.booleanVal);
    }
    /**
     * Effective setting value for aibiDashboardEmbeddingAccessPolicy setting. This is the final effective value of setting. To set a value use aibi_dashboard_embedding_access_policy
     * 
     */
    @Export(name="effectiveAibiDashboardEmbeddingAccessPolicy", refs={AccountSettingV2EffectiveAibiDashboardEmbeddingAccessPolicy.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2EffectiveAibiDashboardEmbeddingAccessPolicy> effectiveAibiDashboardEmbeddingAccessPolicy;

    /**
     * @return Effective setting value for aibiDashboardEmbeddingAccessPolicy setting. This is the final effective value of setting. To set a value use aibi_dashboard_embedding_access_policy
     * 
     */
    public Output<Optional<AccountSettingV2EffectiveAibiDashboardEmbeddingAccessPolicy>> effectiveAibiDashboardEmbeddingAccessPolicy() {
        return Codegen.optional(this.effectiveAibiDashboardEmbeddingAccessPolicy);
    }
    /**
     * Effective setting value for aibiDashboardEmbeddingApprovedDomains setting. This is the final effective value of setting. To set a value use aibi_dashboard_embedding_approved_domains
     * 
     */
    @Export(name="effectiveAibiDashboardEmbeddingApprovedDomains", refs={AccountSettingV2EffectiveAibiDashboardEmbeddingApprovedDomains.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2EffectiveAibiDashboardEmbeddingApprovedDomains> effectiveAibiDashboardEmbeddingApprovedDomains;

    /**
     * @return Effective setting value for aibiDashboardEmbeddingApprovedDomains setting. This is the final effective value of setting. To set a value use aibi_dashboard_embedding_approved_domains
     * 
     */
    public Output<Optional<AccountSettingV2EffectiveAibiDashboardEmbeddingApprovedDomains>> effectiveAibiDashboardEmbeddingApprovedDomains() {
        return Codegen.optional(this.effectiveAibiDashboardEmbeddingApprovedDomains);
    }
    /**
     * Effective setting value for automaticClusterUpdateWorkspace setting. This is the final effective value of setting. To set a value use automatic_cluster_update_workspace
     * 
     */
    @Export(name="effectiveAutomaticClusterUpdateWorkspace", refs={AccountSettingV2EffectiveAutomaticClusterUpdateWorkspace.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2EffectiveAutomaticClusterUpdateWorkspace> effectiveAutomaticClusterUpdateWorkspace;

    /**
     * @return Effective setting value for automaticClusterUpdateWorkspace setting. This is the final effective value of setting. To set a value use automatic_cluster_update_workspace
     * 
     */
    public Output<Optional<AccountSettingV2EffectiveAutomaticClusterUpdateWorkspace>> effectiveAutomaticClusterUpdateWorkspace() {
        return Codegen.optional(this.effectiveAutomaticClusterUpdateWorkspace);
    }
    /**
     * (BooleanMessage) - Effective setting value for boolean type setting. This is the final effective value of setting. To set a value use boolean_val
     * 
     */
    @Export(name="effectiveBooleanVal", refs={AccountSettingV2EffectiveBooleanVal.class}, tree="[0]")
    private Output<AccountSettingV2EffectiveBooleanVal> effectiveBooleanVal;

    /**
     * @return (BooleanMessage) - Effective setting value for boolean type setting. This is the final effective value of setting. To set a value use boolean_val
     * 
     */
    public Output<AccountSettingV2EffectiveBooleanVal> effectiveBooleanVal() {
        return this.effectiveBooleanVal;
    }
    /**
     * (IntegerMessage) - Effective setting value for integer type setting. This is the final effective value of setting. To set a value use integer_val
     * 
     */
    @Export(name="effectiveIntegerVal", refs={AccountSettingV2EffectiveIntegerVal.class}, tree="[0]")
    private Output<AccountSettingV2EffectiveIntegerVal> effectiveIntegerVal;

    /**
     * @return (IntegerMessage) - Effective setting value for integer type setting. This is the final effective value of setting. To set a value use integer_val
     * 
     */
    public Output<AccountSettingV2EffectiveIntegerVal> effectiveIntegerVal() {
        return this.effectiveIntegerVal;
    }
    /**
     * Effective setting value for personalCompute setting. This is the final effective value of setting. To set a value use personal_compute
     * 
     */
    @Export(name="effectivePersonalCompute", refs={AccountSettingV2EffectivePersonalCompute.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2EffectivePersonalCompute> effectivePersonalCompute;

    /**
     * @return Effective setting value for personalCompute setting. This is the final effective value of setting. To set a value use personal_compute
     * 
     */
    public Output<Optional<AccountSettingV2EffectivePersonalCompute>> effectivePersonalCompute() {
        return Codegen.optional(this.effectivePersonalCompute);
    }
    /**
     * Effective setting value for restrictWorkspaceAdmins setting. This is the final effective value of setting. To set a value use restrict_workspace_admins
     * 
     */
    @Export(name="effectiveRestrictWorkspaceAdmins", refs={AccountSettingV2EffectiveRestrictWorkspaceAdmins.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2EffectiveRestrictWorkspaceAdmins> effectiveRestrictWorkspaceAdmins;

    /**
     * @return Effective setting value for restrictWorkspaceAdmins setting. This is the final effective value of setting. To set a value use restrict_workspace_admins
     * 
     */
    public Output<Optional<AccountSettingV2EffectiveRestrictWorkspaceAdmins>> effectiveRestrictWorkspaceAdmins() {
        return Codegen.optional(this.effectiveRestrictWorkspaceAdmins);
    }
    /**
     * (StringMessage) - Effective setting value for string type setting. This is the final effective value of setting. To set a value use string_val
     * 
     */
    @Export(name="effectiveStringVal", refs={AccountSettingV2EffectiveStringVal.class}, tree="[0]")
    private Output<AccountSettingV2EffectiveStringVal> effectiveStringVal;

    /**
     * @return (StringMessage) - Effective setting value for string type setting. This is the final effective value of setting. To set a value use string_val
     * 
     */
    public Output<AccountSettingV2EffectiveStringVal> effectiveStringVal() {
        return this.effectiveStringVal;
    }
    /**
     * Setting value for integer type setting. This is the setting value set by consumers, check effectiveIntegerVal for final setting value
     * 
     */
    @Export(name="integerVal", refs={AccountSettingV2IntegerVal.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2IntegerVal> integerVal;

    /**
     * @return Setting value for integer type setting. This is the setting value set by consumers, check effectiveIntegerVal for final setting value
     * 
     */
    public Output<Optional<AccountSettingV2IntegerVal>> integerVal() {
        return Codegen.optional(this.integerVal);
    }
    /**
     * Name of the setting
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Name of the setting
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Setting value for personalCompute setting. This is the setting value set by consumers, check effectivePersonalCompute for final setting value
     * 
     */
    @Export(name="personalCompute", refs={AccountSettingV2PersonalCompute.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2PersonalCompute> personalCompute;

    /**
     * @return Setting value for personalCompute setting. This is the setting value set by consumers, check effectivePersonalCompute for final setting value
     * 
     */
    public Output<Optional<AccountSettingV2PersonalCompute>> personalCompute() {
        return Codegen.optional(this.personalCompute);
    }
    /**
     * Setting value for restrictWorkspaceAdmins setting. This is the setting value set by consumers, check effectiveRestrictWorkspaceAdmins for final setting value
     * 
     */
    @Export(name="restrictWorkspaceAdmins", refs={AccountSettingV2RestrictWorkspaceAdmins.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2RestrictWorkspaceAdmins> restrictWorkspaceAdmins;

    /**
     * @return Setting value for restrictWorkspaceAdmins setting. This is the setting value set by consumers, check effectiveRestrictWorkspaceAdmins for final setting value
     * 
     */
    public Output<Optional<AccountSettingV2RestrictWorkspaceAdmins>> restrictWorkspaceAdmins() {
        return Codegen.optional(this.restrictWorkspaceAdmins);
    }
    /**
     * Setting value for string type setting. This is the setting value set by consumers, check effectiveStringVal for final setting value
     * 
     */
    @Export(name="stringVal", refs={AccountSettingV2StringVal.class}, tree="[0]")
    private Output</* @Nullable */ AccountSettingV2StringVal> stringVal;

    /**
     * @return Setting value for string type setting. This is the setting value set by consumers, check effectiveStringVal for final setting value
     * 
     */
    public Output<Optional<AccountSettingV2StringVal>> stringVal() {
        return Codegen.optional(this.stringVal);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public AccountSettingV2(java.lang.String name) {
        this(name, AccountSettingV2Args.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public AccountSettingV2(java.lang.String name, @Nullable AccountSettingV2Args args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public AccountSettingV2(java.lang.String name, @Nullable AccountSettingV2Args args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("databricks:index/accountSettingV2:AccountSettingV2", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private AccountSettingV2(java.lang.String name, Output<java.lang.String> id, @Nullable AccountSettingV2State state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("databricks:index/accountSettingV2:AccountSettingV2", name, state, makeResourceOptions(options, id), false);
    }

    private static AccountSettingV2Args makeArgs(@Nullable AccountSettingV2Args args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? AccountSettingV2Args.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static AccountSettingV2 get(java.lang.String name, Output<java.lang.String> id, @Nullable AccountSettingV2State state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new AccountSettingV2(name, id, state, options);
    }
}
