provider: databricks
major-version: 1
env:
  DATABRICKS_USERNAME: ${{ secrets.DATABRICKS_USERNAME }}
  DATABRICKS_PASSWORD: ${{ secrets.DATABRICKS_PASSWORD}}
  DATABRICKS_ACCOUNT_ID: ${{ secrets.DATABRICKS_ACCOUNT_ID}}
  DATABRICKS_HOST: https://accounts.cloud.databricks.com
providerDefaultBranch: main
makeTemplate: bridged
plugins:
  - name: random 
    version: "4.8.2"
  - name: aws 
    version: "5.18.0"
  - name: time
    version: "0.0.13"
  - name: azure
    version: "5.66.1"
  - name: docker
    version: "4.5.1"
