version: "2"
run:
  timeout: 20m
linters:
  enable:
    - goconst
    - gosec
    - lll
    - misspell
    - nakedret
    - revive
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - schema.go
      - pulumiManifest.go
      - pkg/vendored
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - blank
        - default
        - prefix(github.com/pulumi/)
        - prefix(github.com/pulumi/pulumi-databricks)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - schema.go
      - pulumiManifest.go
      - pkg/vendored
      - third_party$
      - builtin$
      - examples$
