// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-databricks/sdk/go/databricks/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// [![Private Preview](https://img.shields.io/badge/Release_Stage-Private_Preview-blueviolet)](https://docs.databricks.com/aws/en/release-notes/release-types)
func GetOnlineStores(ctx *pulumi.Context, args *GetOnlineStoresArgs, opts ...pulumi.InvokeOption) (*GetOnlineStoresResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetOnlineStoresResult
	err := ctx.Invoke("databricks:index/getOnlineStores:getOnlineStores", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOnlineStores.
type GetOnlineStoresArgs struct {
	// The maximum number of results to return. Defaults to 100 if not specified
	PageSize *int `pulumi:"pageSize"`
}

// A collection of values returned by getOnlineStores.
type GetOnlineStoresResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id           string                       `pulumi:"id"`
	OnlineStores []GetOnlineStoresOnlineStore `pulumi:"onlineStores"`
	PageSize     *int                         `pulumi:"pageSize"`
}

func GetOnlineStoresOutput(ctx *pulumi.Context, args GetOnlineStoresOutputArgs, opts ...pulumi.InvokeOption) GetOnlineStoresResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetOnlineStoresResultOutput, error) {
			args := v.(GetOnlineStoresArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("databricks:index/getOnlineStores:getOnlineStores", args, GetOnlineStoresResultOutput{}, options).(GetOnlineStoresResultOutput), nil
		}).(GetOnlineStoresResultOutput)
}

// A collection of arguments for invoking getOnlineStores.
type GetOnlineStoresOutputArgs struct {
	// The maximum number of results to return. Defaults to 100 if not specified
	PageSize pulumi.IntPtrInput `pulumi:"pageSize"`
}

func (GetOnlineStoresOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOnlineStoresArgs)(nil)).Elem()
}

// A collection of values returned by getOnlineStores.
type GetOnlineStoresResultOutput struct{ *pulumi.OutputState }

func (GetOnlineStoresResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOnlineStoresResult)(nil)).Elem()
}

func (o GetOnlineStoresResultOutput) ToGetOnlineStoresResultOutput() GetOnlineStoresResultOutput {
	return o
}

func (o GetOnlineStoresResultOutput) ToGetOnlineStoresResultOutputWithContext(ctx context.Context) GetOnlineStoresResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetOnlineStoresResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetOnlineStoresResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetOnlineStoresResultOutput) OnlineStores() GetOnlineStoresOnlineStoreArrayOutput {
	return o.ApplyT(func(v GetOnlineStoresResult) []GetOnlineStoresOnlineStore { return v.OnlineStores }).(GetOnlineStoresOnlineStoreArrayOutput)
}

func (o GetOnlineStoresResultOutput) PageSize() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetOnlineStoresResult) *int { return v.PageSize }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOnlineStoresResultOutput{})
}
