// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-databricks/sdk/go/databricks/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// [![Private Preview](https://img.shields.io/badge/Release_Stage-Private_Preview-blueviolet)](https://docs.databricks.com/aws/en/release-notes/release-types)
//
// [API Documentation](https://docs.databricks.com/api/workspace/iamv2)
//
// Manages a direct membership of a principal (user, service principal, or group) in a group, scoped to a workspace. Creating the resource adds the member; deleting it removes the member. Membership is immutable — changing the group or principal replaces the resource.
//
// ## Example Usage
//
// Example usage:
//
// Adds a principal as a direct member of a group, using a workspace-scoped
// provider. `groupId` and `principalId` are the internal Databricks IDs of the
// group and the member. Membership is immutable — changing either field replaces
// the resource.
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-databricks/sdk/go/databricks"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := databricks.NewWorkspaceIamDirectGroupMemberV2(ctx, "this", &databricks.WorkspaceIamDirectGroupMemberV2Args{
//				GroupId:     pulumi.Int(123456789),
//				PrincipalId: pulumi.String("987654321"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type WorkspaceIamDirectGroupMemberV2 struct {
	pulumi.CustomResourceState

	// (string) - Display name of the principal
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// (string) - The external ID of the principal in Databricks
	ExternalId pulumi.StringOutput `pulumi:"externalId"`
	// (integer) - The internal ID of the group this member belongs to
	GroupId pulumi.IntOutput `pulumi:"groupId"`
	// (string) - The source of group membership (internal or from identity provider). Possible values are: `IDENTITY_PROVIDER`, `INTERNAL`
	MembershipSource pulumi.StringOutput `pulumi:"membershipSource"`
	// Internal ID of the principal in Databricks
	PrincipalId pulumi.StringOutput `pulumi:"principalId"`
	// (string) - The type of the principal (user/service principal/group). Possible values are: `GROUP`, `SERVICE_PRINCIPAL`, `USER`
	PrincipalType pulumi.StringOutput `pulumi:"principalType"`
	// Configure the provider for management through account provider.
	ProviderConfig WorkspaceIamDirectGroupMemberV2ProviderConfigOutput `pulumi:"providerConfig"`
}

// NewWorkspaceIamDirectGroupMemberV2 registers a new resource with the given unique name, arguments, and options.
func NewWorkspaceIamDirectGroupMemberV2(ctx *pulumi.Context,
	name string, args *WorkspaceIamDirectGroupMemberV2Args, opts ...pulumi.ResourceOption) (*WorkspaceIamDirectGroupMemberV2, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PrincipalId == nil {
		return nil, errors.New("invalid value for required argument 'PrincipalId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource WorkspaceIamDirectGroupMemberV2
	err := ctx.RegisterResource("databricks:index/workspaceIamDirectGroupMemberV2:WorkspaceIamDirectGroupMemberV2", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWorkspaceIamDirectGroupMemberV2 gets an existing WorkspaceIamDirectGroupMemberV2 resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWorkspaceIamDirectGroupMemberV2(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WorkspaceIamDirectGroupMemberV2State, opts ...pulumi.ResourceOption) (*WorkspaceIamDirectGroupMemberV2, error) {
	var resource WorkspaceIamDirectGroupMemberV2
	err := ctx.ReadResource("databricks:index/workspaceIamDirectGroupMemberV2:WorkspaceIamDirectGroupMemberV2", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WorkspaceIamDirectGroupMemberV2 resources.
type workspaceIamDirectGroupMemberV2State struct {
	// (string) - Display name of the principal
	DisplayName *string `pulumi:"displayName"`
	// (string) - The external ID of the principal in Databricks
	ExternalId *string `pulumi:"externalId"`
	// (integer) - The internal ID of the group this member belongs to
	GroupId *int `pulumi:"groupId"`
	// (string) - The source of group membership (internal or from identity provider). Possible values are: `IDENTITY_PROVIDER`, `INTERNAL`
	MembershipSource *string `pulumi:"membershipSource"`
	// Internal ID of the principal in Databricks
	PrincipalId *string `pulumi:"principalId"`
	// (string) - The type of the principal (user/service principal/group). Possible values are: `GROUP`, `SERVICE_PRINCIPAL`, `USER`
	PrincipalType *string `pulumi:"principalType"`
	// Configure the provider for management through account provider.
	ProviderConfig *WorkspaceIamDirectGroupMemberV2ProviderConfig `pulumi:"providerConfig"`
}

type WorkspaceIamDirectGroupMemberV2State struct {
	// (string) - Display name of the principal
	DisplayName pulumi.StringPtrInput
	// (string) - The external ID of the principal in Databricks
	ExternalId pulumi.StringPtrInput
	// (integer) - The internal ID of the group this member belongs to
	GroupId pulumi.IntPtrInput
	// (string) - The source of group membership (internal or from identity provider). Possible values are: `IDENTITY_PROVIDER`, `INTERNAL`
	MembershipSource pulumi.StringPtrInput
	// Internal ID of the principal in Databricks
	PrincipalId pulumi.StringPtrInput
	// (string) - The type of the principal (user/service principal/group). Possible values are: `GROUP`, `SERVICE_PRINCIPAL`, `USER`
	PrincipalType pulumi.StringPtrInput
	// Configure the provider for management through account provider.
	ProviderConfig WorkspaceIamDirectGroupMemberV2ProviderConfigPtrInput
}

func (WorkspaceIamDirectGroupMemberV2State) ElementType() reflect.Type {
	return reflect.TypeOf((*workspaceIamDirectGroupMemberV2State)(nil)).Elem()
}

type workspaceIamDirectGroupMemberV2Args struct {
	// (integer) - The internal ID of the group this member belongs to
	GroupId *int `pulumi:"groupId"`
	// Internal ID of the principal in Databricks
	PrincipalId string `pulumi:"principalId"`
	// Configure the provider for management through account provider.
	ProviderConfig *WorkspaceIamDirectGroupMemberV2ProviderConfig `pulumi:"providerConfig"`
}

// The set of arguments for constructing a WorkspaceIamDirectGroupMemberV2 resource.
type WorkspaceIamDirectGroupMemberV2Args struct {
	// (integer) - The internal ID of the group this member belongs to
	GroupId pulumi.IntPtrInput
	// Internal ID of the principal in Databricks
	PrincipalId pulumi.StringInput
	// Configure the provider for management through account provider.
	ProviderConfig WorkspaceIamDirectGroupMemberV2ProviderConfigPtrInput
}

func (WorkspaceIamDirectGroupMemberV2Args) ElementType() reflect.Type {
	return reflect.TypeOf((*workspaceIamDirectGroupMemberV2Args)(nil)).Elem()
}

type WorkspaceIamDirectGroupMemberV2Input interface {
	pulumi.Input

	ToWorkspaceIamDirectGroupMemberV2Output() WorkspaceIamDirectGroupMemberV2Output
	ToWorkspaceIamDirectGroupMemberV2OutputWithContext(ctx context.Context) WorkspaceIamDirectGroupMemberV2Output
}

func (*WorkspaceIamDirectGroupMemberV2) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkspaceIamDirectGroupMemberV2)(nil)).Elem()
}

func (i *WorkspaceIamDirectGroupMemberV2) ToWorkspaceIamDirectGroupMemberV2Output() WorkspaceIamDirectGroupMemberV2Output {
	return i.ToWorkspaceIamDirectGroupMemberV2OutputWithContext(context.Background())
}

func (i *WorkspaceIamDirectGroupMemberV2) ToWorkspaceIamDirectGroupMemberV2OutputWithContext(ctx context.Context) WorkspaceIamDirectGroupMemberV2Output {
	return pulumi.ToOutputWithContext(ctx, i).(WorkspaceIamDirectGroupMemberV2Output)
}

// WorkspaceIamDirectGroupMemberV2ArrayInput is an input type that accepts WorkspaceIamDirectGroupMemberV2Array and WorkspaceIamDirectGroupMemberV2ArrayOutput values.
// You can construct a concrete instance of `WorkspaceIamDirectGroupMemberV2ArrayInput` via:
//
//	WorkspaceIamDirectGroupMemberV2Array{ WorkspaceIamDirectGroupMemberV2Args{...} }
type WorkspaceIamDirectGroupMemberV2ArrayInput interface {
	pulumi.Input

	ToWorkspaceIamDirectGroupMemberV2ArrayOutput() WorkspaceIamDirectGroupMemberV2ArrayOutput
	ToWorkspaceIamDirectGroupMemberV2ArrayOutputWithContext(context.Context) WorkspaceIamDirectGroupMemberV2ArrayOutput
}

type WorkspaceIamDirectGroupMemberV2Array []WorkspaceIamDirectGroupMemberV2Input

func (WorkspaceIamDirectGroupMemberV2Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkspaceIamDirectGroupMemberV2)(nil)).Elem()
}

func (i WorkspaceIamDirectGroupMemberV2Array) ToWorkspaceIamDirectGroupMemberV2ArrayOutput() WorkspaceIamDirectGroupMemberV2ArrayOutput {
	return i.ToWorkspaceIamDirectGroupMemberV2ArrayOutputWithContext(context.Background())
}

func (i WorkspaceIamDirectGroupMemberV2Array) ToWorkspaceIamDirectGroupMemberV2ArrayOutputWithContext(ctx context.Context) WorkspaceIamDirectGroupMemberV2ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkspaceIamDirectGroupMemberV2ArrayOutput)
}

// WorkspaceIamDirectGroupMemberV2MapInput is an input type that accepts WorkspaceIamDirectGroupMemberV2Map and WorkspaceIamDirectGroupMemberV2MapOutput values.
// You can construct a concrete instance of `WorkspaceIamDirectGroupMemberV2MapInput` via:
//
//	WorkspaceIamDirectGroupMemberV2Map{ "key": WorkspaceIamDirectGroupMemberV2Args{...} }
type WorkspaceIamDirectGroupMemberV2MapInput interface {
	pulumi.Input

	ToWorkspaceIamDirectGroupMemberV2MapOutput() WorkspaceIamDirectGroupMemberV2MapOutput
	ToWorkspaceIamDirectGroupMemberV2MapOutputWithContext(context.Context) WorkspaceIamDirectGroupMemberV2MapOutput
}

type WorkspaceIamDirectGroupMemberV2Map map[string]WorkspaceIamDirectGroupMemberV2Input

func (WorkspaceIamDirectGroupMemberV2Map) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkspaceIamDirectGroupMemberV2)(nil)).Elem()
}

func (i WorkspaceIamDirectGroupMemberV2Map) ToWorkspaceIamDirectGroupMemberV2MapOutput() WorkspaceIamDirectGroupMemberV2MapOutput {
	return i.ToWorkspaceIamDirectGroupMemberV2MapOutputWithContext(context.Background())
}

func (i WorkspaceIamDirectGroupMemberV2Map) ToWorkspaceIamDirectGroupMemberV2MapOutputWithContext(ctx context.Context) WorkspaceIamDirectGroupMemberV2MapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkspaceIamDirectGroupMemberV2MapOutput)
}

type WorkspaceIamDirectGroupMemberV2Output struct{ *pulumi.OutputState }

func (WorkspaceIamDirectGroupMemberV2Output) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkspaceIamDirectGroupMemberV2)(nil)).Elem()
}

func (o WorkspaceIamDirectGroupMemberV2Output) ToWorkspaceIamDirectGroupMemberV2Output() WorkspaceIamDirectGroupMemberV2Output {
	return o
}

func (o WorkspaceIamDirectGroupMemberV2Output) ToWorkspaceIamDirectGroupMemberV2OutputWithContext(ctx context.Context) WorkspaceIamDirectGroupMemberV2Output {
	return o
}

// (string) - Display name of the principal
func (o WorkspaceIamDirectGroupMemberV2Output) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkspaceIamDirectGroupMemberV2) pulumi.StringOutput { return v.DisplayName }).(pulumi.StringOutput)
}

// (string) - The external ID of the principal in Databricks
func (o WorkspaceIamDirectGroupMemberV2Output) ExternalId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkspaceIamDirectGroupMemberV2) pulumi.StringOutput { return v.ExternalId }).(pulumi.StringOutput)
}

// (integer) - The internal ID of the group this member belongs to
func (o WorkspaceIamDirectGroupMemberV2Output) GroupId() pulumi.IntOutput {
	return o.ApplyT(func(v *WorkspaceIamDirectGroupMemberV2) pulumi.IntOutput { return v.GroupId }).(pulumi.IntOutput)
}

// (string) - The source of group membership (internal or from identity provider). Possible values are: `IDENTITY_PROVIDER`, `INTERNAL`
func (o WorkspaceIamDirectGroupMemberV2Output) MembershipSource() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkspaceIamDirectGroupMemberV2) pulumi.StringOutput { return v.MembershipSource }).(pulumi.StringOutput)
}

// Internal ID of the principal in Databricks
func (o WorkspaceIamDirectGroupMemberV2Output) PrincipalId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkspaceIamDirectGroupMemberV2) pulumi.StringOutput { return v.PrincipalId }).(pulumi.StringOutput)
}

// (string) - The type of the principal (user/service principal/group). Possible values are: `GROUP`, `SERVICE_PRINCIPAL`, `USER`
func (o WorkspaceIamDirectGroupMemberV2Output) PrincipalType() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkspaceIamDirectGroupMemberV2) pulumi.StringOutput { return v.PrincipalType }).(pulumi.StringOutput)
}

// Configure the provider for management through account provider.
func (o WorkspaceIamDirectGroupMemberV2Output) ProviderConfig() WorkspaceIamDirectGroupMemberV2ProviderConfigOutput {
	return o.ApplyT(func(v *WorkspaceIamDirectGroupMemberV2) WorkspaceIamDirectGroupMemberV2ProviderConfigOutput {
		return v.ProviderConfig
	}).(WorkspaceIamDirectGroupMemberV2ProviderConfigOutput)
}

type WorkspaceIamDirectGroupMemberV2ArrayOutput struct{ *pulumi.OutputState }

func (WorkspaceIamDirectGroupMemberV2ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkspaceIamDirectGroupMemberV2)(nil)).Elem()
}

func (o WorkspaceIamDirectGroupMemberV2ArrayOutput) ToWorkspaceIamDirectGroupMemberV2ArrayOutput() WorkspaceIamDirectGroupMemberV2ArrayOutput {
	return o
}

func (o WorkspaceIamDirectGroupMemberV2ArrayOutput) ToWorkspaceIamDirectGroupMemberV2ArrayOutputWithContext(ctx context.Context) WorkspaceIamDirectGroupMemberV2ArrayOutput {
	return o
}

func (o WorkspaceIamDirectGroupMemberV2ArrayOutput) Index(i pulumi.IntInput) WorkspaceIamDirectGroupMemberV2Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *WorkspaceIamDirectGroupMemberV2 {
		return vs[0].([]*WorkspaceIamDirectGroupMemberV2)[vs[1].(int)]
	}).(WorkspaceIamDirectGroupMemberV2Output)
}

type WorkspaceIamDirectGroupMemberV2MapOutput struct{ *pulumi.OutputState }

func (WorkspaceIamDirectGroupMemberV2MapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkspaceIamDirectGroupMemberV2)(nil)).Elem()
}

func (o WorkspaceIamDirectGroupMemberV2MapOutput) ToWorkspaceIamDirectGroupMemberV2MapOutput() WorkspaceIamDirectGroupMemberV2MapOutput {
	return o
}

func (o WorkspaceIamDirectGroupMemberV2MapOutput) ToWorkspaceIamDirectGroupMemberV2MapOutputWithContext(ctx context.Context) WorkspaceIamDirectGroupMemberV2MapOutput {
	return o
}

func (o WorkspaceIamDirectGroupMemberV2MapOutput) MapIndex(k pulumi.StringInput) WorkspaceIamDirectGroupMemberV2Output {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *WorkspaceIamDirectGroupMemberV2 {
		return vs[0].(map[string]*WorkspaceIamDirectGroupMemberV2)[vs[1].(string)]
	}).(WorkspaceIamDirectGroupMemberV2Output)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WorkspaceIamDirectGroupMemberV2Input)(nil)).Elem(), &WorkspaceIamDirectGroupMemberV2{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkspaceIamDirectGroupMemberV2ArrayInput)(nil)).Elem(), WorkspaceIamDirectGroupMemberV2Array{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkspaceIamDirectGroupMemberV2MapInput)(nil)).Elem(), WorkspaceIamDirectGroupMemberV2Map{})
	pulumi.RegisterOutputType(WorkspaceIamDirectGroupMemberV2Output{})
	pulumi.RegisterOutputType(WorkspaceIamDirectGroupMemberV2ArrayOutput{})
	pulumi.RegisterOutputType(WorkspaceIamDirectGroupMemberV2MapOutput{})
}
