// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    /// <summary>
    /// [![Private Preview](https://img.shields.io/badge/Release_Stage-Private_Preview-blueviolet)](https://docs.databricks.com/aws/en/release-notes/release-types)
    /// 
    /// User preference is a configurable value that determines how a feature or behavior works for a specific user within the Databricks platform.
    /// 
    /// See user settings-metadata API for list of user preferences that can be modified using this resource.
    /// 
    /// ## Example Usage
    /// 
    /// Setting an account user preference:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Databricks = Pulumi.Databricks;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var themeSetting = new Databricks.Index.AccountUserSettingV2("theme_setting", new()
    ///     {
    ///         UserId = "&lt;user-id&gt;",
    ///         Name = "enableDarkMode",
    ///         StringVal = 
    ///         {
    ///             { "value", "dark" },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// Setting a boolean user preference:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Databricks = Pulumi.Databricks;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var enableLineNumbers = new Databricks.Index.AccountUserSettingV2("enable_line_numbers", new()
    ///     {
    ///         UserId = "&lt;user-id&gt;",
    ///         Name = "enableLineNumbers",
    ///         BooleanVal = 
    ///         {
    ///             { "value", true },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// As of Pulumi v1.5, resources can be imported through configuration.
    /// 
    /// hcl
    /// 
    /// import {
    /// 
    ///   id = "name,user_id"
    /// 
    ///   to = databricks_account_setting_user_preference_v2.this
    /// 
    /// }
    /// 
    /// If you are using an older version of Pulumi, import the resource using the `pulumi import` command as follows:
    /// 
    /// ```sh
    /// $ pulumi import databricks:index/accountSettingUserPreferenceV2:AccountSettingUserPreferenceV2 this "name,user_id"
    /// ```
    /// </summary>
    [DatabricksResourceType("databricks:index/accountSettingUserPreferenceV2:AccountSettingUserPreferenceV2")]
    public partial class AccountSettingUserPreferenceV2 : global::Pulumi.CustomResource
    {
        [Output("booleanVal")]
        public Output<Outputs.AccountSettingUserPreferenceV2BooleanVal?> BooleanVal { get; private set; } = null!;

        /// <summary>
        /// (BooleanMessage)
        /// </summary>
        [Output("effectiveBooleanVal")]
        public Output<Outputs.AccountSettingUserPreferenceV2EffectiveBooleanVal> EffectiveBooleanVal { get; private set; } = null!;

        /// <summary>
        /// (StringMessage)
        /// </summary>
        [Output("effectiveStringVal")]
        public Output<Outputs.AccountSettingUserPreferenceV2EffectiveStringVal> EffectiveStringVal { get; private set; } = null!;

        /// <summary>
        /// Name of the setting
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("stringVal")]
        public Output<Outputs.AccountSettingUserPreferenceV2StringVal?> StringVal { get; private set; } = null!;

        /// <summary>
        /// User ID of the user
        /// </summary>
        [Output("userId")]
        public Output<string?> UserId { get; private set; } = null!;


        /// <summary>
        /// Create a AccountSettingUserPreferenceV2 resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AccountSettingUserPreferenceV2(string name, AccountSettingUserPreferenceV2Args? args = null, CustomResourceOptions? options = null)
            : base("databricks:index/accountSettingUserPreferenceV2:AccountSettingUserPreferenceV2", name, args ?? new AccountSettingUserPreferenceV2Args(), MakeResourceOptions(options, ""))
        {
        }

        private AccountSettingUserPreferenceV2(string name, Input<string> id, AccountSettingUserPreferenceV2State? state = null, CustomResourceOptions? options = null)
            : base("databricks:index/accountSettingUserPreferenceV2:AccountSettingUserPreferenceV2", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AccountSettingUserPreferenceV2 resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AccountSettingUserPreferenceV2 Get(string name, Input<string> id, AccountSettingUserPreferenceV2State? state = null, CustomResourceOptions? options = null)
        {
            return new AccountSettingUserPreferenceV2(name, id, state, options);
        }
    }

    public sealed class AccountSettingUserPreferenceV2Args : global::Pulumi.ResourceArgs
    {
        [Input("booleanVal")]
        public Input<Inputs.AccountSettingUserPreferenceV2BooleanValArgs>? BooleanVal { get; set; }

        /// <summary>
        /// Name of the setting
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("stringVal")]
        public Input<Inputs.AccountSettingUserPreferenceV2StringValArgs>? StringVal { get; set; }

        /// <summary>
        /// User ID of the user
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public AccountSettingUserPreferenceV2Args()
        {
        }
        public static new AccountSettingUserPreferenceV2Args Empty => new AccountSettingUserPreferenceV2Args();
    }

    public sealed class AccountSettingUserPreferenceV2State : global::Pulumi.ResourceArgs
    {
        [Input("booleanVal")]
        public Input<Inputs.AccountSettingUserPreferenceV2BooleanValGetArgs>? BooleanVal { get; set; }

        /// <summary>
        /// (BooleanMessage)
        /// </summary>
        [Input("effectiveBooleanVal")]
        public Input<Inputs.AccountSettingUserPreferenceV2EffectiveBooleanValGetArgs>? EffectiveBooleanVal { get; set; }

        /// <summary>
        /// (StringMessage)
        /// </summary>
        [Input("effectiveStringVal")]
        public Input<Inputs.AccountSettingUserPreferenceV2EffectiveStringValGetArgs>? EffectiveStringVal { get; set; }

        /// <summary>
        /// Name of the setting
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("stringVal")]
        public Input<Inputs.AccountSettingUserPreferenceV2StringValGetArgs>? StringVal { get; set; }

        /// <summary>
        /// User ID of the user
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public AccountSettingUserPreferenceV2State()
        {
        }
        public static new AccountSettingUserPreferenceV2State Empty => new AccountSettingUserPreferenceV2State();
    }
}
