// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.databricks.outputs.GetAccountNetworkPoliciesItemEgress;
import com.pulumi.databricks.outputs.GetAccountNetworkPoliciesItemIngress;
import com.pulumi.databricks.outputs.GetAccountNetworkPoliciesItemIngressDryRun;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetAccountNetworkPoliciesItem {
    /**
     * @return (string) - The associated account ID for this Network Policy object
     * 
     */
    private String accountId;
    /**
     * @return (NetworkPolicyEgress) - The network policies applying for egress traffic
     * 
     */
    private GetAccountNetworkPoliciesItemEgress egress;
    /**
     * @return (CustomerFacingIngressNetworkPolicy) - The network policies applying for ingress traffic
     * 
     */
    private GetAccountNetworkPoliciesItemIngress ingress;
    /**
     * @return (CustomerFacingIngressNetworkPolicy) - The ingress policy for dry run mode. Dry run will always run even if the request
     * is allowed by the ingress policy. When this field is set, the policy will be evaluated
     * and emit logs only without blocking requests
     * 
     */
    private GetAccountNetworkPoliciesItemIngressDryRun ingressDryRun;
    /**
     * @return (string) - The unique identifier for the network policy
     * 
     */
    private String networkPolicyId;

    private GetAccountNetworkPoliciesItem() {}
    /**
     * @return (string) - The associated account ID for this Network Policy object
     * 
     */
    public String accountId() {
        return this.accountId;
    }
    /**
     * @return (NetworkPolicyEgress) - The network policies applying for egress traffic
     * 
     */
    public GetAccountNetworkPoliciesItemEgress egress() {
        return this.egress;
    }
    /**
     * @return (CustomerFacingIngressNetworkPolicy) - The network policies applying for ingress traffic
     * 
     */
    public GetAccountNetworkPoliciesItemIngress ingress() {
        return this.ingress;
    }
    /**
     * @return (CustomerFacingIngressNetworkPolicy) - The ingress policy for dry run mode. Dry run will always run even if the request
     * is allowed by the ingress policy. When this field is set, the policy will be evaluated
     * and emit logs only without blocking requests
     * 
     */
    public GetAccountNetworkPoliciesItemIngressDryRun ingressDryRun() {
        return this.ingressDryRun;
    }
    /**
     * @return (string) - The unique identifier for the network policy
     * 
     */
    public String networkPolicyId() {
        return this.networkPolicyId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountNetworkPoliciesItem defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accountId;
        private GetAccountNetworkPoliciesItemEgress egress;
        private GetAccountNetworkPoliciesItemIngress ingress;
        private GetAccountNetworkPoliciesItemIngressDryRun ingressDryRun;
        private String networkPolicyId;
        public Builder() {}
        public Builder(GetAccountNetworkPoliciesItem defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.egress = defaults.egress;
    	      this.ingress = defaults.ingress;
    	      this.ingressDryRun = defaults.ingressDryRun;
    	      this.networkPolicyId = defaults.networkPolicyId;
        }

        @CustomType.Setter
        public Builder accountId(String accountId) {
            if (accountId == null) {
              throw new MissingRequiredPropertyException("GetAccountNetworkPoliciesItem", "accountId");
            }
            this.accountId = accountId;
            return this;
        }
        @CustomType.Setter
        public Builder egress(GetAccountNetworkPoliciesItemEgress egress) {
            if (egress == null) {
              throw new MissingRequiredPropertyException("GetAccountNetworkPoliciesItem", "egress");
            }
            this.egress = egress;
            return this;
        }
        @CustomType.Setter
        public Builder ingress(GetAccountNetworkPoliciesItemIngress ingress) {
            if (ingress == null) {
              throw new MissingRequiredPropertyException("GetAccountNetworkPoliciesItem", "ingress");
            }
            this.ingress = ingress;
            return this;
        }
        @CustomType.Setter
        public Builder ingressDryRun(GetAccountNetworkPoliciesItemIngressDryRun ingressDryRun) {
            if (ingressDryRun == null) {
              throw new MissingRequiredPropertyException("GetAccountNetworkPoliciesItem", "ingressDryRun");
            }
            this.ingressDryRun = ingressDryRun;
            return this;
        }
        @CustomType.Setter
        public Builder networkPolicyId(String networkPolicyId) {
            if (networkPolicyId == null) {
              throw new MissingRequiredPropertyException("GetAccountNetworkPoliciesItem", "networkPolicyId");
            }
            this.networkPolicyId = networkPolicyId;
            return this;
        }
        public GetAccountNetworkPoliciesItem build() {
            final var _resultValue = new GetAccountNetworkPoliciesItem();
            _resultValue.accountId = accountId;
            _resultValue.egress = egress;
            _resultValue.ingress = ingress;
            _resultValue.ingressDryRun = ingressDryRun;
            _resultValue.networkPolicyId = networkPolicyId;
            return _resultValue;
        }
    }
}
