// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.databricks.outputs.GetDatabaseInstancesDatabaseInstance;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetDatabaseInstancesResult {
    private List<GetDatabaseInstancesDatabaseInstance> databaseInstances;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private @Nullable String workspaceId;

    private GetDatabaseInstancesResult() {}
    public List<GetDatabaseInstancesDatabaseInstance> databaseInstances() {
        return this.databaseInstances;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public Optional<String> workspaceId() {
        return Optional.ofNullable(this.workspaceId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDatabaseInstancesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetDatabaseInstancesDatabaseInstance> databaseInstances;
        private String id;
        private @Nullable String workspaceId;
        public Builder() {}
        public Builder(GetDatabaseInstancesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.databaseInstances = defaults.databaseInstances;
    	      this.id = defaults.id;
    	      this.workspaceId = defaults.workspaceId;
        }

        @CustomType.Setter
        public Builder databaseInstances(List<GetDatabaseInstancesDatabaseInstance> databaseInstances) {
            if (databaseInstances == null) {
              throw new MissingRequiredPropertyException("GetDatabaseInstancesResult", "databaseInstances");
            }
            this.databaseInstances = databaseInstances;
            return this;
        }
        public Builder databaseInstances(GetDatabaseInstancesDatabaseInstance... databaseInstances) {
            return databaseInstances(List.of(databaseInstances));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetDatabaseInstancesResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder workspaceId(@Nullable String workspaceId) {

            this.workspaceId = workspaceId;
            return this;
        }
        public GetDatabaseInstancesResult build() {
            final var _resultValue = new GetDatabaseInstancesResult();
            _resultValue.databaseInstances = databaseInstances;
            _resultValue.id = id;
            _resultValue.workspaceId = workspaceId;
            return _resultValue;
        }
    }
}
