// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.databricks.outputs.GetJobJobSettingsSettingsTaskNewClusterInitScriptAbfss;
import com.pulumi.databricks.outputs.GetJobJobSettingsSettingsTaskNewClusterInitScriptDbfs;
import com.pulumi.databricks.outputs.GetJobJobSettingsSettingsTaskNewClusterInitScriptFile;
import com.pulumi.databricks.outputs.GetJobJobSettingsSettingsTaskNewClusterInitScriptGcs;
import com.pulumi.databricks.outputs.GetJobJobSettingsSettingsTaskNewClusterInitScriptS3;
import com.pulumi.databricks.outputs.GetJobJobSettingsSettingsTaskNewClusterInitScriptVolumes;
import com.pulumi.databricks.outputs.GetJobJobSettingsSettingsTaskNewClusterInitScriptWorkspace;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetJobJobSettingsSettingsTaskNewClusterInitScript {
    private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptAbfss abfss;
    private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptDbfs dbfs;
    private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptFile file;
    private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptGcs gcs;
    private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptS3 s3;
    private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptVolumes volumes;
    private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptWorkspace workspace;

    private GetJobJobSettingsSettingsTaskNewClusterInitScript() {}
    public Optional<GetJobJobSettingsSettingsTaskNewClusterInitScriptAbfss> abfss() {
        return Optional.ofNullable(this.abfss);
    }
    public Optional<GetJobJobSettingsSettingsTaskNewClusterInitScriptDbfs> dbfs() {
        return Optional.ofNullable(this.dbfs);
    }
    public Optional<GetJobJobSettingsSettingsTaskNewClusterInitScriptFile> file() {
        return Optional.ofNullable(this.file);
    }
    public Optional<GetJobJobSettingsSettingsTaskNewClusterInitScriptGcs> gcs() {
        return Optional.ofNullable(this.gcs);
    }
    public Optional<GetJobJobSettingsSettingsTaskNewClusterInitScriptS3> s3() {
        return Optional.ofNullable(this.s3);
    }
    public Optional<GetJobJobSettingsSettingsTaskNewClusterInitScriptVolumes> volumes() {
        return Optional.ofNullable(this.volumes);
    }
    public Optional<GetJobJobSettingsSettingsTaskNewClusterInitScriptWorkspace> workspace() {
        return Optional.ofNullable(this.workspace);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetJobJobSettingsSettingsTaskNewClusterInitScript defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptAbfss abfss;
        private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptDbfs dbfs;
        private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptFile file;
        private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptGcs gcs;
        private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptS3 s3;
        private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptVolumes volumes;
        private @Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptWorkspace workspace;
        public Builder() {}
        public Builder(GetJobJobSettingsSettingsTaskNewClusterInitScript defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.abfss = defaults.abfss;
    	      this.dbfs = defaults.dbfs;
    	      this.file = defaults.file;
    	      this.gcs = defaults.gcs;
    	      this.s3 = defaults.s3;
    	      this.volumes = defaults.volumes;
    	      this.workspace = defaults.workspace;
        }

        @CustomType.Setter
        public Builder abfss(@Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptAbfss abfss) {

            this.abfss = abfss;
            return this;
        }
        @CustomType.Setter
        public Builder dbfs(@Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptDbfs dbfs) {

            this.dbfs = dbfs;
            return this;
        }
        @CustomType.Setter
        public Builder file(@Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptFile file) {

            this.file = file;
            return this;
        }
        @CustomType.Setter
        public Builder gcs(@Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptGcs gcs) {

            this.gcs = gcs;
            return this;
        }
        @CustomType.Setter
        public Builder s3(@Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptS3 s3) {

            this.s3 = s3;
            return this;
        }
        @CustomType.Setter
        public Builder volumes(@Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptVolumes volumes) {

            this.volumes = volumes;
            return this;
        }
        @CustomType.Setter
        public Builder workspace(@Nullable GetJobJobSettingsSettingsTaskNewClusterInitScriptWorkspace workspace) {

            this.workspace = workspace;
            return this;
        }
        public GetJobJobSettingsSettingsTaskNewClusterInitScript build() {
            final var _resultValue = new GetJobJobSettingsSettingsTaskNewClusterInitScript();
            _resultValue.abfss = abfss;
            _resultValue.dbfs = dbfs;
            _resultValue.file = file;
            _resultValue.gcs = gcs;
            _resultValue.s3 = s3;
            _resultValue.volumes = volumes;
            _resultValue.workspace = workspace;
            return _resultValue;
        }
    }
}
