// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetPostgresEndpointStatusHosts {
    /**
     * @return (string) - The hostname to connect to this endpoint. For read-write endpoints, this is a read-write hostname which connects
     * to the primary compute. For read-only endpoints, this is a read-only hostname which allows read-only operations
     * 
     */
    private String host;

    private GetPostgresEndpointStatusHosts() {}
    /**
     * @return (string) - The hostname to connect to this endpoint. For read-write endpoints, this is a read-write hostname which connects
     * to the primary compute. For read-only endpoints, this is a read-only hostname which allows read-only operations
     * 
     */
    public String host() {
        return this.host;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPostgresEndpointStatusHosts defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String host;
        public Builder() {}
        public Builder(GetPostgresEndpointStatusHosts defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.host = defaults.host;
        }

        @CustomType.Setter
        public Builder host(String host) {
            if (host == null) {
              throw new MissingRequiredPropertyException("GetPostgresEndpointStatusHosts", "host");
            }
            this.host = host;
            return this;
        }
        public GetPostgresEndpointStatusHosts build() {
            final var _resultValue = new GetPostgresEndpointStatusHosts();
            _resultValue.host = host;
            return _resultValue;
        }
    }
}
