// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetRegisteredModelModelInfoAlias {
    /**
     * @return string with the name of alias
     * 
     */
    private @Nullable String aliasName;
    /**
     * @return The name of the catalog where the schema and the registered model reside.
     * 
     */
    private @Nullable String catalogName;
    private @Nullable String id;
    private @Nullable String modelName;
    /**
     * @return The name of the schema where the registered model resides.
     * 
     */
    private @Nullable String schemaName;
    /**
     * @return associated model version
     * 
     */
    private @Nullable Integer versionNum;

    private GetRegisteredModelModelInfoAlias() {}
    /**
     * @return string with the name of alias
     * 
     */
    public Optional<String> aliasName() {
        return Optional.ofNullable(this.aliasName);
    }
    /**
     * @return The name of the catalog where the schema and the registered model reside.
     * 
     */
    public Optional<String> catalogName() {
        return Optional.ofNullable(this.catalogName);
    }
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    public Optional<String> modelName() {
        return Optional.ofNullable(this.modelName);
    }
    /**
     * @return The name of the schema where the registered model resides.
     * 
     */
    public Optional<String> schemaName() {
        return Optional.ofNullable(this.schemaName);
    }
    /**
     * @return associated model version
     * 
     */
    public Optional<Integer> versionNum() {
        return Optional.ofNullable(this.versionNum);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRegisteredModelModelInfoAlias defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String aliasName;
        private @Nullable String catalogName;
        private @Nullable String id;
        private @Nullable String modelName;
        private @Nullable String schemaName;
        private @Nullable Integer versionNum;
        public Builder() {}
        public Builder(GetRegisteredModelModelInfoAlias defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.aliasName = defaults.aliasName;
    	      this.catalogName = defaults.catalogName;
    	      this.id = defaults.id;
    	      this.modelName = defaults.modelName;
    	      this.schemaName = defaults.schemaName;
    	      this.versionNum = defaults.versionNum;
        }

        @CustomType.Setter
        public Builder aliasName(@Nullable String aliasName) {

            this.aliasName = aliasName;
            return this;
        }
        @CustomType.Setter
        public Builder catalogName(@Nullable String catalogName) {

            this.catalogName = catalogName;
            return this;
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder modelName(@Nullable String modelName) {

            this.modelName = modelName;
            return this;
        }
        @CustomType.Setter
        public Builder schemaName(@Nullable String schemaName) {

            this.schemaName = schemaName;
            return this;
        }
        @CustomType.Setter
        public Builder versionNum(@Nullable Integer versionNum) {

            this.versionNum = versionNum;
            return this;
        }
        public GetRegisteredModelModelInfoAlias build() {
            final var _resultValue = new GetRegisteredModelModelInfoAlias();
            _resultValue.aliasName = aliasName;
            _resultValue.catalogName = catalogName;
            _resultValue.id = id;
            _resultValue.modelName = modelName;
            _resultValue.schemaName = schemaName;
            _resultValue.versionNum = versionNum;
            return _resultValue;
        }
    }
}
