// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class JobTaskForEachTaskTaskDbtPlatformTask {
    /**
     * @return The resource name of the UC connection to authenticate from Databricks to Power BI
     * 
     */
    private @Nullable String connectionResourceName;
    private @Nullable String dbtPlatformJobId;

    private JobTaskForEachTaskTaskDbtPlatformTask() {}
    /**
     * @return The resource name of the UC connection to authenticate from Databricks to Power BI
     * 
     */
    public Optional<String> connectionResourceName() {
        return Optional.ofNullable(this.connectionResourceName);
    }
    public Optional<String> dbtPlatformJobId() {
        return Optional.ofNullable(this.dbtPlatformJobId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(JobTaskForEachTaskTaskDbtPlatformTask defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String connectionResourceName;
        private @Nullable String dbtPlatformJobId;
        public Builder() {}
        public Builder(JobTaskForEachTaskTaskDbtPlatformTask defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.connectionResourceName = defaults.connectionResourceName;
    	      this.dbtPlatformJobId = defaults.dbtPlatformJobId;
        }

        @CustomType.Setter
        public Builder connectionResourceName(@Nullable String connectionResourceName) {

            this.connectionResourceName = connectionResourceName;
            return this;
        }
        @CustomType.Setter
        public Builder dbtPlatformJobId(@Nullable String dbtPlatformJobId) {

            this.dbtPlatformJobId = dbtPlatformJobId;
            return this;
        }
        public JobTaskForEachTaskTaskDbtPlatformTask build() {
            final var _resultValue = new JobTaskForEachTaskTaskDbtPlatformTask();
            _resultValue.connectionResourceName = connectionResourceName;
            _resultValue.dbtPlatformJobId = dbtPlatformJobId;
            return _resultValue;
        }
    }
}
