// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class SupervisorAgentToolUcFunction {
    /**
     * @return (string) - Full resource name:
     * supervisor-agents/{supervisor_agent_id}/tools/{tool_id}
     * 
     */
    private String name;

    private SupervisorAgentToolUcFunction() {}
    /**
     * @return (string) - Full resource name:
     * supervisor-agents/{supervisor_agent_id}/tools/{tool_id}
     * 
     */
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SupervisorAgentToolUcFunction defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        public Builder() {}
        public Builder(SupervisorAgentToolUcFunction defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("SupervisorAgentToolUcFunction", "name");
            }
            this.name = name;
            return this;
        }
        public SupervisorAgentToolUcFunction build() {
            final var _resultValue = new SupervisorAgentToolUcFunction();
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
