// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Outputs
{

    [OutputType]
    public sealed class AppResource
    {
        public readonly Outputs.AppResourceApp? App;
        /// <summary>
        /// attribute
        /// </summary>
        public readonly Outputs.AppResourceDatabase? Database;
        /// <summary>
        /// The description of the resource.
        /// 
        /// Exactly one of the following attributes must be provided:
        /// </summary>
        public readonly string? Description;
        public readonly Outputs.AppResourceExperiment? Experiment;
        /// <summary>
        /// attribute
        /// </summary>
        public readonly Outputs.AppResourceGenieSpace? GenieSpace;
        /// <summary>
        /// attribute
        /// </summary>
        public readonly Outputs.AppResourceJob? Job;
        /// <summary>
        /// The name of the resource.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// attribute
        /// </summary>
        public readonly Outputs.AppResourceSecret? Secret;
        /// <summary>
        /// attribute
        /// </summary>
        public readonly Outputs.AppResourceServingEndpoint? ServingEndpoint;
        /// <summary>
        /// attribute
        /// </summary>
        public readonly Outputs.AppResourceSqlWarehouse? SqlWarehouse;
        /// <summary>
        /// attribute (see the [API docs](https://docs.databricks.com/api/workspace/apps/create#resources-uc_securable) for full list of supported UC objects)
        /// </summary>
        public readonly Outputs.AppResourceUcSecurable? UcSecurable;

        [OutputConstructor]
        private AppResource(
            Outputs.AppResourceApp? app,

            Outputs.AppResourceDatabase? database,

            string? description,

            Outputs.AppResourceExperiment? experiment,

            Outputs.AppResourceGenieSpace? genieSpace,

            Outputs.AppResourceJob? job,

            string name,

            Outputs.AppResourceSecret? secret,

            Outputs.AppResourceServingEndpoint? servingEndpoint,

            Outputs.AppResourceSqlWarehouse? sqlWarehouse,

            Outputs.AppResourceUcSecurable? ucSecurable)
        {
            App = app;
            Database = database;
            Description = description;
            Experiment = experiment;
            GenieSpace = genieSpace;
            Job = job;
            Name = name;
            Secret = secret;
            ServingEndpoint = servingEndpoint;
            SqlWarehouse = sqlWarehouse;
            UcSecurable = ucSecurable;
        }
    }
}
