// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Outputs
{

    [OutputType]
    public sealed class GetAlertsV2AlertEvaluationNotificationResult
    {
        public readonly bool EffectiveNotifyOnOk;
        public readonly int EffectiveRetriggerSeconds;
        /// <summary>
        /// (boolean) - Whether to notify alert subscribers when alert returns back to normal
        /// </summary>
        public readonly bool? NotifyOnOk;
        /// <summary>
        /// (integer) - Number of seconds an alert waits after being triggered before it is allowed to send another notification.
        /// If set to 0 or omitted, the alert will not send any further notifications after the first trigger
        /// Setting this value to 1 allows the alert to send a notification on every evaluation where the condition is met, effectively making it always retrigger for notification purposes
        /// </summary>
        public readonly int? RetriggerSeconds;
        /// <summary>
        /// (list of AlertV2Subscription)
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAlertsV2AlertEvaluationNotificationSubscriptionResult> Subscriptions;

        [OutputConstructor]
        private GetAlertsV2AlertEvaluationNotificationResult(
            bool effectiveNotifyOnOk,

            int effectiveRetriggerSeconds,

            bool? notifyOnOk,

            int? retriggerSeconds,

            ImmutableArray<Outputs.GetAlertsV2AlertEvaluationNotificationSubscriptionResult> subscriptions)
        {
            EffectiveNotifyOnOk = effectiveNotifyOnOk;
            EffectiveRetriggerSeconds = effectiveRetriggerSeconds;
            NotifyOnOk = notifyOnOk;
            RetriggerSeconds = retriggerSeconds;
            Subscriptions = subscriptions;
        }
    }
}
