// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Outputs
{

    [OutputType]
    public sealed class GetFunctionsFunctionReturnParamParameterResult
    {
        public readonly string? Comment;
        public readonly string Name;
        public readonly string? ParameterDefault;
        public readonly string? ParameterMode;
        public readonly string? ParameterType;
        public readonly int Position;
        public readonly string? TypeIntervalType;
        public readonly string? TypeJson;
        public readonly string TypeName;
        public readonly int? TypePrecision;
        public readonly int? TypeScale;
        public readonly string TypeText;

        [OutputConstructor]
        private GetFunctionsFunctionReturnParamParameterResult(
            string? comment,

            string name,

            string? parameterDefault,

            string? parameterMode,

            string? parameterType,

            int position,

            string? typeIntervalType,

            string? typeJson,

            string typeName,

            int? typePrecision,

            int? typeScale,

            string typeText)
        {
            Comment = comment;
            Name = name;
            ParameterDefault = parameterDefault;
            ParameterMode = parameterMode;
            ParameterType = parameterType;
            Position = position;
            TypeIntervalType = typeIntervalType;
            TypeJson = typeJson;
            TypeName = typeName;
            TypePrecision = typePrecision;
            TypeScale = typeScale;
            TypeText = typeText;
        }
    }
}
