// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Outputs
{

    [OutputType]
    public sealed class GetFeatureEngineeringKafkaConfigIngestionConfigBackfillSourceResult
    {
        /// <summary>
        /// (string) - The full three-part name (catalog, schema, name) of the Delta table to be created for ingestion
        /// </summary>
        public readonly string? DeltaTableName;
        /// <summary>
        /// (DeltaTableSource, deprecated) - Deprecated: Use DeltaTableName instead. Kept for backwards compatibility.
        /// The Delta table source containing the historical data to backfill.
        /// Only the delta table name is used for backfill, other fields are ignored
        /// </summary>
        public readonly Outputs.GetFeatureEngineeringKafkaConfigIngestionConfigBackfillSourceDeltaTableSourceResult? DeltaTableSource;

        [OutputConstructor]
        private GetFeatureEngineeringKafkaConfigIngestionConfigBackfillSourceResult(
            string? deltaTableName,

            Outputs.GetFeatureEngineeringKafkaConfigIngestionConfigBackfillSourceDeltaTableSourceResult? deltaTableSource)
        {
            DeltaTableName = deltaTableName;
            DeltaTableSource = deltaTableSource;
        }
    }
}
