// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Outputs
{

    [OutputType]
    public sealed class GetFeatureEngineeringFeatureTimeWindowContinuousResult
    {
        /// <summary>
        /// (string) - The offset of the continuous window (must be non-positive)
        /// </summary>
        public readonly string? Offset;
        /// <summary>
        /// (string) - The duration of each tumbling window (non-overlapping, fixed-duration windows)
        /// </summary>
        public readonly string WindowDuration;

        [OutputConstructor]
        private GetFeatureEngineeringFeatureTimeWindowContinuousResult(
            string? offset,

            string windowDuration)
        {
            Offset = offset;
            WindowDuration = windowDuration;
        }
    }
}
