// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Outputs
{

    [OutputType]
    public sealed class MwsNccPrivateEndpointRuleGcpEndpoint
    {
        public readonly bool? AllVpcScServices;
        public readonly Outputs.MwsNccPrivateEndpointRuleGcpEndpointGoogleApiEndpoints? GoogleApiEndpoints;
        public readonly string? PscEndpointUri;
        public readonly string? ServiceAttachment;

        [OutputConstructor]
        private MwsNccPrivateEndpointRuleGcpEndpoint(
            bool? allVpcScServices,

            Outputs.MwsNccPrivateEndpointRuleGcpEndpointGoogleApiEndpoints? googleApiEndpoints,

            string? pscEndpointUri,

            string? serviceAttachment)
        {
            AllVpcScServices = allVpcScServices;
            GoogleApiEndpoints = googleApiEndpoints;
            PscEndpointUri = pscEndpointUri;
            ServiceAttachment = serviceAttachment;
        }
    }
}
