// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Outputs
{

    [OutputType]
    public sealed class PipelineIngestionDefinitionObjectSchemaConnectorOptions
    {
        public readonly Outputs.PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptions? GdriveOptions;
        public readonly Outputs.PipelineIngestionDefinitionObjectSchemaConnectorOptionsGoogleAdsOptions? GoogleAdsOptions;
        public readonly Outputs.PipelineIngestionDefinitionObjectSchemaConnectorOptionsSharepointOptions? SharepointOptions;
        public readonly Outputs.PipelineIngestionDefinitionObjectSchemaConnectorOptionsTiktokAdsOptions? TiktokAdsOptions;

        [OutputConstructor]
        private PipelineIngestionDefinitionObjectSchemaConnectorOptions(
            Outputs.PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptions? gdriveOptions,

            Outputs.PipelineIngestionDefinitionObjectSchemaConnectorOptionsGoogleAdsOptions? googleAdsOptions,

            Outputs.PipelineIngestionDefinitionObjectSchemaConnectorOptionsSharepointOptions? sharepointOptions,

            Outputs.PipelineIngestionDefinitionObjectSchemaConnectorOptionsTiktokAdsOptions? tiktokAdsOptions)
        {
            GdriveOptions = gdriveOptions;
            GoogleAdsOptions = googleAdsOptions;
            SharepointOptions = sharepointOptions;
            TiktokAdsOptions = tiktokAdsOptions;
        }
    }
}
