name: Download the provider binary
description: Downloads the provider binary to `bin/`.

runs:
  using: "composite"
  steps:

    - name: Download pulumi-resource-databricks
      uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
      with:
        pattern: pulumi-resource-databricks-*-linux-amd64.tar.gz
        path: ${{ github.workspace }}/bin
        merge-multiple: true

    - name: Untar pulumi-resource-databricks
      shell: bash
      run: |
        tar -zxf ${{ github.workspace }}/bin/*amd64.tar.gz -C ${{ github.workspace}}/bin

    - name: Mark pulumi-resource-databricks as executable
      shell: bash
      run: |
        find ${{ github.workspace }} -name "pulumi-*-databricks" -print -exec chmod +x {} \;
