// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AiGatewayModelServiceConfigInferenceTableArgs extends com.pulumi.resources.ResourceArgs {

    public static final AiGatewayModelServiceConfigInferenceTableArgs Empty = new AiGatewayModelServiceConfigInferenceTableArgs();

    /**
     * (boolean) - Whether the destination&#39;s backing model or model provider service has
     * been deleted. The destination remains visible so you can identify the
     * broken dependency. Requests cannot use this destination until the backing
     * resource is restored or the destination is replaced
     * 
     */
    @Import(name="isDeleted")
    private @Nullable Output<Boolean> isDeleted;

    /**
     * @return (boolean) - Whether the destination&#39;s backing model or model provider service has
     * been deleted. The destination remains visible so you can identify the
     * broken dependency. Requests cannot use this destination until the backing
     * resource is restored or the destination is replaced
     * 
     */
    public Optional<Output<Boolean>> isDeleted() {
        return Optional.ofNullable(this.isDeleted);
    }

    /**
     * Name of the parent schema.
     * Format: `schemas/{catalog}.{schema}`.
     * Each `{...}` component is capped at 255 characters individually
     * 
     */
    @Import(name="parent", required=true)
    private Output<String> parent;

    /**
     * @return Name of the parent schema.
     * Format: `schemas/{catalog}.{schema}`.
     * Each `{...}` component is capped at 255 characters individually
     * 
     */
    public Output<String> parent() {
        return this.parent;
    }

    /**
     * (string) - Resolved UC table for payload logs.
     * Format: `tables/{catalog}.{schema}.{table}`
     * 
     */
    @Import(name="table")
    private @Nullable Output<String> table;

    /**
     * @return (string) - Resolved UC table for payload logs.
     * Format: `tables/{catalog}.{schema}.{table}`
     * 
     */
    public Optional<Output<String>> table() {
        return Optional.ofNullable(this.table);
    }

    /**
     * Prefix used to form the inference table&#39;s registered name. AI Gateway
     * appends `_payload`; for example, `tableNamePrefix = &#34;orders&#34;` creates
     * `ordersPayload`. If unset, the prefix defaults to the service name. Read
     * `table` from the response for the resulting resource name. After the
     * inference table is created, this field cannot be changed
     * 
     */
    @Import(name="tableNamePrefix")
    private @Nullable Output<String> tableNamePrefix;

    /**
     * @return Prefix used to form the inference table&#39;s registered name. AI Gateway
     * appends `_payload`; for example, `tableNamePrefix = &#34;orders&#34;` creates
     * `ordersPayload`. If unset, the prefix defaults to the service name. Read
     * `table` from the response for the resulting resource name. After the
     * inference table is created, this field cannot be changed
     * 
     */
    public Optional<Output<String>> tableNamePrefix() {
        return Optional.ofNullable(this.tableNamePrefix);
    }

    private AiGatewayModelServiceConfigInferenceTableArgs() {}

    private AiGatewayModelServiceConfigInferenceTableArgs(AiGatewayModelServiceConfigInferenceTableArgs $) {
        this.isDeleted = $.isDeleted;
        this.parent = $.parent;
        this.table = $.table;
        this.tableNamePrefix = $.tableNamePrefix;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AiGatewayModelServiceConfigInferenceTableArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AiGatewayModelServiceConfigInferenceTableArgs $;

        public Builder() {
            $ = new AiGatewayModelServiceConfigInferenceTableArgs();
        }

        public Builder(AiGatewayModelServiceConfigInferenceTableArgs defaults) {
            $ = new AiGatewayModelServiceConfigInferenceTableArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param isDeleted (boolean) - Whether the destination&#39;s backing model or model provider service has
         * been deleted. The destination remains visible so you can identify the
         * broken dependency. Requests cannot use this destination until the backing
         * resource is restored or the destination is replaced
         * 
         * @return builder
         * 
         */
        public Builder isDeleted(@Nullable Output<Boolean> isDeleted) {
            $.isDeleted = isDeleted;
            return this;
        }

        /**
         * @param isDeleted (boolean) - Whether the destination&#39;s backing model or model provider service has
         * been deleted. The destination remains visible so you can identify the
         * broken dependency. Requests cannot use this destination until the backing
         * resource is restored or the destination is replaced
         * 
         * @return builder
         * 
         */
        public Builder isDeleted(Boolean isDeleted) {
            return isDeleted(Output.of(isDeleted));
        }

        /**
         * @param parent Name of the parent schema.
         * Format: `schemas/{catalog}.{schema}`.
         * Each `{...}` component is capped at 255 characters individually
         * 
         * @return builder
         * 
         */
        public Builder parent(Output<String> parent) {
            $.parent = parent;
            return this;
        }

        /**
         * @param parent Name of the parent schema.
         * Format: `schemas/{catalog}.{schema}`.
         * Each `{...}` component is capped at 255 characters individually
         * 
         * @return builder
         * 
         */
        public Builder parent(String parent) {
            return parent(Output.of(parent));
        }

        /**
         * @param table (string) - Resolved UC table for payload logs.
         * Format: `tables/{catalog}.{schema}.{table}`
         * 
         * @return builder
         * 
         */
        public Builder table(@Nullable Output<String> table) {
            $.table = table;
            return this;
        }

        /**
         * @param table (string) - Resolved UC table for payload logs.
         * Format: `tables/{catalog}.{schema}.{table}`
         * 
         * @return builder
         * 
         */
        public Builder table(String table) {
            return table(Output.of(table));
        }

        /**
         * @param tableNamePrefix Prefix used to form the inference table&#39;s registered name. AI Gateway
         * appends `_payload`; for example, `tableNamePrefix = &#34;orders&#34;` creates
         * `ordersPayload`. If unset, the prefix defaults to the service name. Read
         * `table` from the response for the resulting resource name. After the
         * inference table is created, this field cannot be changed
         * 
         * @return builder
         * 
         */
        public Builder tableNamePrefix(@Nullable Output<String> tableNamePrefix) {
            $.tableNamePrefix = tableNamePrefix;
            return this;
        }

        /**
         * @param tableNamePrefix Prefix used to form the inference table&#39;s registered name. AI Gateway
         * appends `_payload`; for example, `tableNamePrefix = &#34;orders&#34;` creates
         * `ordersPayload`. If unset, the prefix defaults to the service name. Read
         * `table` from the response for the resulting resource name. After the
         * inference table is created, this field cannot be changed
         * 
         * @return builder
         * 
         */
        public Builder tableNamePrefix(String tableNamePrefix) {
            return tableNamePrefix(Output.of(tableNamePrefix));
        }

        public AiGatewayModelServiceConfigInferenceTableArgs build() {
            if ($.parent == null) {
                throw new MissingRequiredPropertyException("AiGatewayModelServiceConfigInferenceTableArgs", "parent");
            }
            return $;
        }
    }

}
