// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetAccountIamGroupV2Args extends com.pulumi.resources.InvokeArgs {

    public static final GetAccountIamGroupV2Args Empty = new GetAccountIamGroupV2Args();

    /**
     * Internal group ID of the group in Databricks
     * 
     */
    @Import(name="groupId", required=true)
    private Output<String> groupId;

    /**
     * @return Internal group ID of the group in Databricks
     * 
     */
    public Output<String> groupId() {
        return this.groupId;
    }

    private GetAccountIamGroupV2Args() {}

    private GetAccountIamGroupV2Args(GetAccountIamGroupV2Args $) {
        this.groupId = $.groupId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAccountIamGroupV2Args defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAccountIamGroupV2Args $;

        public Builder() {
            $ = new GetAccountIamGroupV2Args();
        }

        public Builder(GetAccountIamGroupV2Args defaults) {
            $ = new GetAccountIamGroupV2Args(Objects.requireNonNull(defaults));
        }

        /**
         * @param groupId Internal group ID of the group in Databricks
         * 
         * @return builder
         * 
         */
        public Builder groupId(Output<String> groupId) {
            $.groupId = groupId;
            return this;
        }

        /**
         * @param groupId Internal group ID of the group in Databricks
         * 
         * @return builder
         * 
         */
        public Builder groupId(String groupId) {
            return groupId(Output.of(groupId));
        }

        public GetAccountIamGroupV2Args build() {
            if ($.groupId == null) {
                throw new MissingRequiredPropertyException("GetAccountIamGroupV2Args", "groupId");
            }
            return $;
        }
    }

}
