// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetClusterClusterInfoSpecInitScriptGcsArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetClusterClusterInfoSpecInitScriptGcsArgs Empty = new GetClusterClusterInfoSpecInitScriptGcsArgs();

    @Import(name="destination", required=true)
    private Output<String> destination;

    public Output<String> destination() {
        return this.destination;
    }

    private GetClusterClusterInfoSpecInitScriptGcsArgs() {}

    private GetClusterClusterInfoSpecInitScriptGcsArgs(GetClusterClusterInfoSpecInitScriptGcsArgs $) {
        this.destination = $.destination;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetClusterClusterInfoSpecInitScriptGcsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetClusterClusterInfoSpecInitScriptGcsArgs $;

        public Builder() {
            $ = new GetClusterClusterInfoSpecInitScriptGcsArgs();
        }

        public Builder(GetClusterClusterInfoSpecInitScriptGcsArgs defaults) {
            $ = new GetClusterClusterInfoSpecInitScriptGcsArgs(Objects.requireNonNull(defaults));
        }

        public Builder destination(Output<String> destination) {
            $.destination = destination;
            return this;
        }

        public Builder destination(String destination) {
            return destination(Output.of(destination));
        }

        public GetClusterClusterInfoSpecInitScriptGcsArgs build() {
            if ($.destination == null) {
                throw new MissingRequiredPropertyException("GetClusterClusterInfoSpecInitScriptGcsArgs", "destination");
            }
            return $;
        }
    }

}
