// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetStorageCredentialStorageCredentialInfoAzureManagedIdentity extends com.pulumi.resources.InvokeArgs {

    public static final GetStorageCredentialStorageCredentialInfoAzureManagedIdentity Empty = new GetStorageCredentialStorageCredentialInfoAzureManagedIdentity();

    @Import(name="accessConnectorId", required=true)
    private String accessConnectorId;

    public String accessConnectorId() {
        return this.accessConnectorId;
    }

    @Import(name="credentialId")
    private @Nullable String credentialId;

    public Optional<String> credentialId() {
        return Optional.ofNullable(this.credentialId);
    }

    @Import(name="managedIdentityId")
    private @Nullable String managedIdentityId;

    public Optional<String> managedIdentityId() {
        return Optional.ofNullable(this.managedIdentityId);
    }

    private GetStorageCredentialStorageCredentialInfoAzureManagedIdentity() {}

    private GetStorageCredentialStorageCredentialInfoAzureManagedIdentity(GetStorageCredentialStorageCredentialInfoAzureManagedIdentity $) {
        this.accessConnectorId = $.accessConnectorId;
        this.credentialId = $.credentialId;
        this.managedIdentityId = $.managedIdentityId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetStorageCredentialStorageCredentialInfoAzureManagedIdentity defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetStorageCredentialStorageCredentialInfoAzureManagedIdentity $;

        public Builder() {
            $ = new GetStorageCredentialStorageCredentialInfoAzureManagedIdentity();
        }

        public Builder(GetStorageCredentialStorageCredentialInfoAzureManagedIdentity defaults) {
            $ = new GetStorageCredentialStorageCredentialInfoAzureManagedIdentity(Objects.requireNonNull(defaults));
        }

        public Builder accessConnectorId(String accessConnectorId) {
            $.accessConnectorId = accessConnectorId;
            return this;
        }

        public Builder credentialId(@Nullable String credentialId) {
            $.credentialId = credentialId;
            return this;
        }

        public Builder managedIdentityId(@Nullable String managedIdentityId) {
            $.managedIdentityId = managedIdentityId;
            return this;
        }

        public GetStorageCredentialStorageCredentialInfoAzureManagedIdentity build() {
            if ($.accessConnectorId == null) {
                throw new MissingRequiredPropertyException("GetStorageCredentialStorageCredentialInfoAzureManagedIdentity", "accessConnectorId");
            }
            return $;
        }
    }

}
