// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.databricks.inputs.GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigApiKeyAuthArgs;
import com.pulumi.databricks.inputs.GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigBearerTokenAuthArgs;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs Empty = new GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs();

    @Import(name="apiKeyAuths")
    private @Nullable Output<List<GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigApiKeyAuthArgs>> apiKeyAuths;

    public Optional<Output<List<GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigApiKeyAuthArgs>>> apiKeyAuths() {
        return Optional.ofNullable(this.apiKeyAuths);
    }

    @Import(name="bearerTokenAuths")
    private @Nullable Output<List<GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigBearerTokenAuthArgs>> bearerTokenAuths;

    public Optional<Output<List<GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigBearerTokenAuthArgs>>> bearerTokenAuths() {
        return Optional.ofNullable(this.bearerTokenAuths);
    }

    @Import(name="customProviderUrl", required=true)
    private Output<String> customProviderUrl;

    public Output<String> customProviderUrl() {
        return this.customProviderUrl;
    }

    private GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs() {}

    private GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs(GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs $) {
        this.apiKeyAuths = $.apiKeyAuths;
        this.bearerTokenAuths = $.bearerTokenAuths;
        this.customProviderUrl = $.customProviderUrl;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs $;

        public Builder() {
            $ = new GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs();
        }

        public Builder(GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs defaults) {
            $ = new GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs(Objects.requireNonNull(defaults));
        }

        public Builder apiKeyAuths(@Nullable Output<List<GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigApiKeyAuthArgs>> apiKeyAuths) {
            $.apiKeyAuths = apiKeyAuths;
            return this;
        }

        public Builder apiKeyAuths(List<GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigApiKeyAuthArgs> apiKeyAuths) {
            return apiKeyAuths(Output.of(apiKeyAuths));
        }

        public Builder apiKeyAuths(GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigApiKeyAuthArgs... apiKeyAuths) {
            return apiKeyAuths(List.of(apiKeyAuths));
        }

        public Builder bearerTokenAuths(@Nullable Output<List<GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigBearerTokenAuthArgs>> bearerTokenAuths) {
            $.bearerTokenAuths = bearerTokenAuths;
            return this;
        }

        public Builder bearerTokenAuths(List<GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigBearerTokenAuthArgs> bearerTokenAuths) {
            return bearerTokenAuths(Output.of(bearerTokenAuths));
        }

        public Builder bearerTokenAuths(GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigBearerTokenAuthArgs... bearerTokenAuths) {
            return bearerTokenAuths(List.of(bearerTokenAuths));
        }

        public Builder customProviderUrl(Output<String> customProviderUrl) {
            $.customProviderUrl = customProviderUrl;
            return this;
        }

        public Builder customProviderUrl(String customProviderUrl) {
            return customProviderUrl(Output.of(customProviderUrl));
        }

        public GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs build() {
            if ($.customProviderUrl == null) {
                throw new MissingRequiredPropertyException("GetServingEndpointsEndpointConfigServedEntityExternalModelCustomProviderConfigArgs", "customProviderUrl");
            }
            return $;
        }
    }

}
