// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class JobTaskSparkPythonTaskArgs extends com.pulumi.resources.ResourceArgs {

    public static final JobTaskSparkPythonTaskArgs Empty = new JobTaskSparkPythonTaskArgs();

    /**
     * (Map) parameters to be used for each run of this task. The SQL alert task does not support custom parameters.
     * 
     */
    @Import(name="parameters")
    private @Nullable Output<List<String>> parameters;

    /**
     * @return (Map) parameters to be used for each run of this task. The SQL alert task does not support custom parameters.
     * 
     */
    public Optional<Output<List<String>>> parameters() {
        return Optional.ofNullable(this.parameters);
    }

    /**
     * The URI of the Python file to be executed. databricks.DbfsFile and S3 paths are supported. This field is required.
     * 
     */
    @Import(name="pythonFile", required=true)
    private Output<String> pythonFile;

    /**
     * @return The URI of the Python file to be executed. databricks.DbfsFile and S3 paths are supported. This field is required.
     * 
     */
    public Output<String> pythonFile() {
        return this.pythonFile;
    }

    private JobTaskSparkPythonTaskArgs() {}

    private JobTaskSparkPythonTaskArgs(JobTaskSparkPythonTaskArgs $) {
        this.parameters = $.parameters;
        this.pythonFile = $.pythonFile;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(JobTaskSparkPythonTaskArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private JobTaskSparkPythonTaskArgs $;

        public Builder() {
            $ = new JobTaskSparkPythonTaskArgs();
        }

        public Builder(JobTaskSparkPythonTaskArgs defaults) {
            $ = new JobTaskSparkPythonTaskArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param parameters (Map) parameters to be used for each run of this task. The SQL alert task does not support custom parameters.
         * 
         * @return builder
         * 
         */
        public Builder parameters(@Nullable Output<List<String>> parameters) {
            $.parameters = parameters;
            return this;
        }

        /**
         * @param parameters (Map) parameters to be used for each run of this task. The SQL alert task does not support custom parameters.
         * 
         * @return builder
         * 
         */
        public Builder parameters(List<String> parameters) {
            return parameters(Output.of(parameters));
        }

        /**
         * @param parameters (Map) parameters to be used for each run of this task. The SQL alert task does not support custom parameters.
         * 
         * @return builder
         * 
         */
        public Builder parameters(String... parameters) {
            return parameters(List.of(parameters));
        }

        /**
         * @param pythonFile The URI of the Python file to be executed. databricks.DbfsFile and S3 paths are supported. This field is required.
         * 
         * @return builder
         * 
         */
        public Builder pythonFile(Output<String> pythonFile) {
            $.pythonFile = pythonFile;
            return this;
        }

        /**
         * @param pythonFile The URI of the Python file to be executed. databricks.DbfsFile and S3 paths are supported. This field is required.
         * 
         * @return builder
         * 
         */
        public Builder pythonFile(String pythonFile) {
            return pythonFile(Output.of(pythonFile));
        }

        public JobTaskSparkPythonTaskArgs build() {
            $.pythonFile = Objects.requireNonNull($.pythonFile, "expected parameter 'pythonFile' to be non-null");
            return $;
        }
    }

}
