// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.databricks.inputs.MasonManagedMemoryEntryProviderConfigArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class MasonManagedMemoryEntryState extends com.pulumi.resources.ResourceArgs {

    public static final MasonManagedMemoryEntryState Empty = new MasonManagedMemoryEntryState();

    /**
     * Customer-provided identifier for the actor whose memory this entry represents
     * 
     */
    @Import(name="actorId")
    private @Nullable Output<String> actorId;

    /**
     * @return Customer-provided identifier for the actor whose memory this entry represents
     * 
     */
    public Optional<Output<String>> actorId() {
        return Optional.ofNullable(this.actorId);
    }

    /**
     * Optional free-form memory content
     * 
     */
    @Import(name="content")
    private @Nullable Output<String> content;

    /**
     * @return Optional free-form memory content
     * 
     */
    public Optional<Output<String>> content() {
        return Optional.ofNullable(this.content);
    }

    /**
     * (string) - Time when the entry was created
     * 
     */
    @Import(name="createTime")
    private @Nullable Output<String> createTime;

    /**
     * @return (string) - Time when the entry was created
     * 
     */
    public Optional<Output<String>> createTime() {
        return Optional.ofNullable(this.createTime);
    }

    /**
     * Human-readable description of the memory entry
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Human-readable description of the memory entry
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Optional caller-selected managed memory entry ID. The service generates an ID when omitted
     * 
     */
    @Import(name="managedMemoryEntryId")
    private @Nullable Output<String> managedMemoryEntryId;

    /**
     * @return Optional caller-selected managed memory entry ID. The service generates an ID when omitted
     * 
     */
    public Optional<Output<String>> managedMemoryEntryId() {
        return Optional.ofNullable(this.managedMemoryEntryId);
    }

    /**
     * (string) - Resource name in the form
     * `memory-stores/{managed_memory_store_id}/entries/{managed_memory_entry_id}`
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return (string) - Resource name in the form
     * `memory-stores/{managed_memory_store_id}/entries/{managed_memory_entry_id}`
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Managed memory store that will contain the entry, in the form
     * `memory-stores/{managed_memory_store_id}`
     * 
     */
    @Import(name="parent")
    private @Nullable Output<String> parent;

    /**
     * @return Managed memory store that will contain the entry, in the form
     * `memory-stores/{managed_memory_store_id}`
     * 
     */
    public Optional<Output<String>> parent() {
        return Optional.ofNullable(this.parent);
    }

    /**
     * Absolute, case-sensitive path identifying the entry within its actor and optional session.
     * Paths must begin with `/` and must not contain empty, `.` or `..` segments
     * 
     */
    @Import(name="path")
    private @Nullable Output<String> path;

    /**
     * @return Absolute, case-sensitive path identifying the entry within its actor and optional session.
     * Paths must begin with `/` and must not contain empty, `.` or `..` segments
     * 
     */
    public Optional<Output<String>> path() {
        return Optional.ofNullable(this.path);
    }

    /**
     * Configure the provider for management through account provider.
     * 
     */
    @Import(name="providerConfig")
    private @Nullable Output<MasonManagedMemoryEntryProviderConfigArgs> providerConfig;

    /**
     * @return Configure the provider for management through account provider.
     * 
     */
    public Optional<Output<MasonManagedMemoryEntryProviderConfigArgs>> providerConfig() {
        return Optional.ofNullable(this.providerConfig);
    }

    /**
     * Optional identifier for the session associated with this memory entry. When omitted, the
     * entry applies across the actor&#39;s sessions
     * 
     */
    @Import(name="sessionId")
    private @Nullable Output<String> sessionId;

    /**
     * @return Optional identifier for the session associated with this memory entry. When omitted, the
     * entry applies across the actor&#39;s sessions
     * 
     */
    public Optional<Output<String>> sessionId() {
        return Optional.ofNullable(this.sessionId);
    }

    /**
     * Which writer created this entry. Caller sets this on Create; immutable after creation. Possible values are: `MANAGED_MEMORY_ENTRY_SOURCE_TYPE_AGENT`, `MANAGED_MEMORY_ENTRY_SOURCE_TYPE_DREAMER`
     * 
     */
    @Import(name="sourceType")
    private @Nullable Output<String> sourceType;

    /**
     * @return Which writer created this entry. Caller sets this on Create; immutable after creation. Possible values are: `MANAGED_MEMORY_ENTRY_SOURCE_TYPE_AGENT`, `MANAGED_MEMORY_ENTRY_SOURCE_TYPE_DREAMER`
     * 
     */
    public Optional<Output<String>> sourceType() {
        return Optional.ofNullable(this.sourceType);
    }

    /**
     * (string) - Time when the entry was last updated
     * 
     */
    @Import(name="updateTime")
    private @Nullable Output<String> updateTime;

    /**
     * @return (string) - Time when the entry was last updated
     * 
     */
    public Optional<Output<String>> updateTime() {
        return Optional.ofNullable(this.updateTime);
    }

    private MasonManagedMemoryEntryState() {}

    private MasonManagedMemoryEntryState(MasonManagedMemoryEntryState $) {
        this.actorId = $.actorId;
        this.content = $.content;
        this.createTime = $.createTime;
        this.description = $.description;
        this.managedMemoryEntryId = $.managedMemoryEntryId;
        this.name = $.name;
        this.parent = $.parent;
        this.path = $.path;
        this.providerConfig = $.providerConfig;
        this.sessionId = $.sessionId;
        this.sourceType = $.sourceType;
        this.updateTime = $.updateTime;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(MasonManagedMemoryEntryState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private MasonManagedMemoryEntryState $;

        public Builder() {
            $ = new MasonManagedMemoryEntryState();
        }

        public Builder(MasonManagedMemoryEntryState defaults) {
            $ = new MasonManagedMemoryEntryState(Objects.requireNonNull(defaults));
        }

        /**
         * @param actorId Customer-provided identifier for the actor whose memory this entry represents
         * 
         * @return builder
         * 
         */
        public Builder actorId(@Nullable Output<String> actorId) {
            $.actorId = actorId;
            return this;
        }

        /**
         * @param actorId Customer-provided identifier for the actor whose memory this entry represents
         * 
         * @return builder
         * 
         */
        public Builder actorId(String actorId) {
            return actorId(Output.of(actorId));
        }

        /**
         * @param content Optional free-form memory content
         * 
         * @return builder
         * 
         */
        public Builder content(@Nullable Output<String> content) {
            $.content = content;
            return this;
        }

        /**
         * @param content Optional free-form memory content
         * 
         * @return builder
         * 
         */
        public Builder content(String content) {
            return content(Output.of(content));
        }

        /**
         * @param createTime (string) - Time when the entry was created
         * 
         * @return builder
         * 
         */
        public Builder createTime(@Nullable Output<String> createTime) {
            $.createTime = createTime;
            return this;
        }

        /**
         * @param createTime (string) - Time when the entry was created
         * 
         * @return builder
         * 
         */
        public Builder createTime(String createTime) {
            return createTime(Output.of(createTime));
        }

        /**
         * @param description Human-readable description of the memory entry
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Human-readable description of the memory entry
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param managedMemoryEntryId Optional caller-selected managed memory entry ID. The service generates an ID when omitted
         * 
         * @return builder
         * 
         */
        public Builder managedMemoryEntryId(@Nullable Output<String> managedMemoryEntryId) {
            $.managedMemoryEntryId = managedMemoryEntryId;
            return this;
        }

        /**
         * @param managedMemoryEntryId Optional caller-selected managed memory entry ID. The service generates an ID when omitted
         * 
         * @return builder
         * 
         */
        public Builder managedMemoryEntryId(String managedMemoryEntryId) {
            return managedMemoryEntryId(Output.of(managedMemoryEntryId));
        }

        /**
         * @param name (string) - Resource name in the form
         * `memory-stores/{managed_memory_store_id}/entries/{managed_memory_entry_id}`
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name (string) - Resource name in the form
         * `memory-stores/{managed_memory_store_id}/entries/{managed_memory_entry_id}`
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param parent Managed memory store that will contain the entry, in the form
         * `memory-stores/{managed_memory_store_id}`
         * 
         * @return builder
         * 
         */
        public Builder parent(@Nullable Output<String> parent) {
            $.parent = parent;
            return this;
        }

        /**
         * @param parent Managed memory store that will contain the entry, in the form
         * `memory-stores/{managed_memory_store_id}`
         * 
         * @return builder
         * 
         */
        public Builder parent(String parent) {
            return parent(Output.of(parent));
        }

        /**
         * @param path Absolute, case-sensitive path identifying the entry within its actor and optional session.
         * Paths must begin with `/` and must not contain empty, `.` or `..` segments
         * 
         * @return builder
         * 
         */
        public Builder path(@Nullable Output<String> path) {
            $.path = path;
            return this;
        }

        /**
         * @param path Absolute, case-sensitive path identifying the entry within its actor and optional session.
         * Paths must begin with `/` and must not contain empty, `.` or `..` segments
         * 
         * @return builder
         * 
         */
        public Builder path(String path) {
            return path(Output.of(path));
        }

        /**
         * @param providerConfig Configure the provider for management through account provider.
         * 
         * @return builder
         * 
         */
        public Builder providerConfig(@Nullable Output<MasonManagedMemoryEntryProviderConfigArgs> providerConfig) {
            $.providerConfig = providerConfig;
            return this;
        }

        /**
         * @param providerConfig Configure the provider for management through account provider.
         * 
         * @return builder
         * 
         */
        public Builder providerConfig(MasonManagedMemoryEntryProviderConfigArgs providerConfig) {
            return providerConfig(Output.of(providerConfig));
        }

        /**
         * @param sessionId Optional identifier for the session associated with this memory entry. When omitted, the
         * entry applies across the actor&#39;s sessions
         * 
         * @return builder
         * 
         */
        public Builder sessionId(@Nullable Output<String> sessionId) {
            $.sessionId = sessionId;
            return this;
        }

        /**
         * @param sessionId Optional identifier for the session associated with this memory entry. When omitted, the
         * entry applies across the actor&#39;s sessions
         * 
         * @return builder
         * 
         */
        public Builder sessionId(String sessionId) {
            return sessionId(Output.of(sessionId));
        }

        /**
         * @param sourceType Which writer created this entry. Caller sets this on Create; immutable after creation. Possible values are: `MANAGED_MEMORY_ENTRY_SOURCE_TYPE_AGENT`, `MANAGED_MEMORY_ENTRY_SOURCE_TYPE_DREAMER`
         * 
         * @return builder
         * 
         */
        public Builder sourceType(@Nullable Output<String> sourceType) {
            $.sourceType = sourceType;
            return this;
        }

        /**
         * @param sourceType Which writer created this entry. Caller sets this on Create; immutable after creation. Possible values are: `MANAGED_MEMORY_ENTRY_SOURCE_TYPE_AGENT`, `MANAGED_MEMORY_ENTRY_SOURCE_TYPE_DREAMER`
         * 
         * @return builder
         * 
         */
        public Builder sourceType(String sourceType) {
            return sourceType(Output.of(sourceType));
        }

        /**
         * @param updateTime (string) - Time when the entry was last updated
         * 
         * @return builder
         * 
         */
        public Builder updateTime(@Nullable Output<String> updateTime) {
            $.updateTime = updateTime;
            return this;
        }

        /**
         * @param updateTime (string) - Time when the entry was last updated
         * 
         * @return builder
         * 
         */
        public Builder updateTime(String updateTime) {
            return updateTime(Output.of(updateTime));
        }

        public MasonManagedMemoryEntryState build() {
            return $;
        }
    }

}
