// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.databricks.inputs.PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsFileIngestionOptionsArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsArgs extends com.pulumi.resources.ResourceArgs {

    public static final PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsArgs Empty = new PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsArgs();

    @Import(name="entityType")
    private @Nullable Output<String> entityType;

    public Optional<Output<String>> entityType() {
        return Optional.ofNullable(this.entityType);
    }

    @Import(name="fileIngestionOptions")
    private @Nullable Output<PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsFileIngestionOptionsArgs> fileIngestionOptions;

    public Optional<Output<PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsFileIngestionOptionsArgs>> fileIngestionOptions() {
        return Optional.ofNullable(this.fileIngestionOptions);
    }

    /**
     * URL of the Lakeflow Declarative Pipeline on the given workspace.
     * 
     */
    @Import(name="url")
    private @Nullable Output<String> url;

    /**
     * @return URL of the Lakeflow Declarative Pipeline on the given workspace.
     * 
     */
    public Optional<Output<String>> url() {
        return Optional.ofNullable(this.url);
    }

    private PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsArgs() {}

    private PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsArgs(PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsArgs $) {
        this.entityType = $.entityType;
        this.fileIngestionOptions = $.fileIngestionOptions;
        this.url = $.url;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsArgs $;

        public Builder() {
            $ = new PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsArgs();
        }

        public Builder(PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsArgs defaults) {
            $ = new PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsArgs(Objects.requireNonNull(defaults));
        }

        public Builder entityType(@Nullable Output<String> entityType) {
            $.entityType = entityType;
            return this;
        }

        public Builder entityType(String entityType) {
            return entityType(Output.of(entityType));
        }

        public Builder fileIngestionOptions(@Nullable Output<PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsFileIngestionOptionsArgs> fileIngestionOptions) {
            $.fileIngestionOptions = fileIngestionOptions;
            return this;
        }

        public Builder fileIngestionOptions(PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsFileIngestionOptionsArgs fileIngestionOptions) {
            return fileIngestionOptions(Output.of(fileIngestionOptions));
        }

        /**
         * @param url URL of the Lakeflow Declarative Pipeline on the given workspace.
         * 
         * @return builder
         * 
         */
        public Builder url(@Nullable Output<String> url) {
            $.url = url;
            return this;
        }

        /**
         * @param url URL of the Lakeflow Declarative Pipeline on the given workspace.
         * 
         * @return builder
         * 
         */
        public Builder url(String url) {
            return url(Output.of(url));
        }

        public PipelineIngestionDefinitionObjectSchemaConnectorOptionsGdriveOptionsArgs build() {
            return $;
        }
    }

}
