// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.databricks.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.databricks.inputs.PostgresProjectInitialEndpointSpecArgs;
import com.pulumi.databricks.inputs.PostgresProjectProviderConfigArgs;
import com.pulumi.databricks.inputs.PostgresProjectSpecArgs;
import com.pulumi.databricks.inputs.PostgresProjectStatusArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PostgresProjectState extends com.pulumi.resources.ResourceArgs {

    public static final PostgresProjectState Empty = new PostgresProjectState();

    /**
     * (string) - A timestamp indicating when the project was created
     * 
     */
    @Import(name="createTime")
    private @Nullable Output<String> createTime;

    /**
     * @return (string) - A timestamp indicating when the project was created
     * 
     */
    public Optional<Output<String>> createTime() {
        return Optional.ofNullable(this.createTime);
    }

    /**
     * (string) - A timestamp indicating when the project was soft-deleted.
     * Empty if the project is not deleted, otherwise set to a timestamp in the past
     * 
     */
    @Import(name="deleteTime")
    private @Nullable Output<String> deleteTime;

    /**
     * @return (string) - A timestamp indicating when the project was soft-deleted.
     * Empty if the project is not deleted, otherwise set to a timestamp in the past
     * 
     */
    public Optional<Output<String>> deleteTime() {
        return Optional.ofNullable(this.deleteTime);
    }

    /**
     * Configuration settings for the initial Read/Write endpoint created inside the initial branch for a newly
     * created project. If omitted, the initial endpoint created will have default settings, without high availability
     * configured. This field does not apply to any endpoints created after project creation. Use
     * spec.default_endpoint_settings to configure default settings for endpoints created after project creation
     * 
     */
    @Import(name="initialEndpointSpec")
    private @Nullable Output<PostgresProjectInitialEndpointSpecArgs> initialEndpointSpec;

    /**
     * @return Configuration settings for the initial Read/Write endpoint created inside the initial branch for a newly
     * created project. If omitted, the initial endpoint created will have default settings, without high availability
     * configured. This field does not apply to any endpoints created after project creation. Use
     * spec.default_endpoint_settings to configure default settings for endpoints created after project creation
     * 
     */
    public Optional<Output<PostgresProjectInitialEndpointSpecArgs>> initialEndpointSpec() {
        return Optional.ofNullable(this.initialEndpointSpec);
    }

    /**
     * (string) - Output only. The full resource path of the project.
     * Format: projects/{project_id}
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return (string) - Output only. The full resource path of the project.
     * Format: projects/{project_id}
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The part of the name, chosen by the user when the resource was created
     * 
     */
    @Import(name="projectId")
    private @Nullable Output<String> projectId;

    /**
     * @return The part of the name, chosen by the user when the resource was created
     * 
     */
    public Optional<Output<String>> projectId() {
        return Optional.ofNullable(this.projectId);
    }

    /**
     * Configure the provider for management through account provider.
     * 
     */
    @Import(name="providerConfig")
    private @Nullable Output<PostgresProjectProviderConfigArgs> providerConfig;

    /**
     * @return Configure the provider for management through account provider.
     * 
     */
    public Optional<Output<PostgresProjectProviderConfigArgs>> providerConfig() {
        return Optional.ofNullable(this.providerConfig);
    }

    /**
     * If true, permanently deletes the project (hard delete).
     * If false or unset, performs a soft delete
     * 
     */
    @Import(name="purgeOnDelete")
    private @Nullable Output<Boolean> purgeOnDelete;

    /**
     * @return If true, permanently deletes the project (hard delete).
     * If false or unset, performs a soft delete
     * 
     */
    public Optional<Output<Boolean>> purgeOnDelete() {
        return Optional.ofNullable(this.purgeOnDelete);
    }

    /**
     * (string) - A timestamp indicating when the project is scheduled for permanent deletion.
     * Empty if the project is not deleted, otherwise set to a timestamp in the future
     * 
     */
    @Import(name="purgeTime")
    private @Nullable Output<String> purgeTime;

    /**
     * @return (string) - A timestamp indicating when the project is scheduled for permanent deletion.
     * Empty if the project is not deleted, otherwise set to a timestamp in the future
     * 
     */
    public Optional<Output<String>> purgeTime() {
        return Optional.ofNullable(this.purgeTime);
    }

    /**
     * The spec contains the project configuration, including display_name, pgVersion (Postgres version), history_retention_duration, and default_endpoint_settings
     * 
     */
    @Import(name="spec")
    private @Nullable Output<PostgresProjectSpecArgs> spec;

    /**
     * @return The spec contains the project configuration, including display_name, pgVersion (Postgres version), history_retention_duration, and default_endpoint_settings
     * 
     */
    public Optional<Output<PostgresProjectSpecArgs>> spec() {
        return Optional.ofNullable(this.spec);
    }

    /**
     * (ProjectStatus) - The current status of a Project
     * 
     */
    @Import(name="status")
    private @Nullable Output<PostgresProjectStatusArgs> status;

    /**
     * @return (ProjectStatus) - The current status of a Project
     * 
     */
    public Optional<Output<PostgresProjectStatusArgs>> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * (string) - System-generated unique ID for the project
     * 
     */
    @Import(name="uid")
    private @Nullable Output<String> uid;

    /**
     * @return (string) - System-generated unique ID for the project
     * 
     */
    public Optional<Output<String>> uid() {
        return Optional.ofNullable(this.uid);
    }

    /**
     * (string) - A timestamp indicating when the project was last updated
     * 
     */
    @Import(name="updateTime")
    private @Nullable Output<String> updateTime;

    /**
     * @return (string) - A timestamp indicating when the project was last updated
     * 
     */
    public Optional<Output<String>> updateTime() {
        return Optional.ofNullable(this.updateTime);
    }

    private PostgresProjectState() {}

    private PostgresProjectState(PostgresProjectState $) {
        this.createTime = $.createTime;
        this.deleteTime = $.deleteTime;
        this.initialEndpointSpec = $.initialEndpointSpec;
        this.name = $.name;
        this.projectId = $.projectId;
        this.providerConfig = $.providerConfig;
        this.purgeOnDelete = $.purgeOnDelete;
        this.purgeTime = $.purgeTime;
        this.spec = $.spec;
        this.status = $.status;
        this.uid = $.uid;
        this.updateTime = $.updateTime;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PostgresProjectState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PostgresProjectState $;

        public Builder() {
            $ = new PostgresProjectState();
        }

        public Builder(PostgresProjectState defaults) {
            $ = new PostgresProjectState(Objects.requireNonNull(defaults));
        }

        /**
         * @param createTime (string) - A timestamp indicating when the project was created
         * 
         * @return builder
         * 
         */
        public Builder createTime(@Nullable Output<String> createTime) {
            $.createTime = createTime;
            return this;
        }

        /**
         * @param createTime (string) - A timestamp indicating when the project was created
         * 
         * @return builder
         * 
         */
        public Builder createTime(String createTime) {
            return createTime(Output.of(createTime));
        }

        /**
         * @param deleteTime (string) - A timestamp indicating when the project was soft-deleted.
         * Empty if the project is not deleted, otherwise set to a timestamp in the past
         * 
         * @return builder
         * 
         */
        public Builder deleteTime(@Nullable Output<String> deleteTime) {
            $.deleteTime = deleteTime;
            return this;
        }

        /**
         * @param deleteTime (string) - A timestamp indicating when the project was soft-deleted.
         * Empty if the project is not deleted, otherwise set to a timestamp in the past
         * 
         * @return builder
         * 
         */
        public Builder deleteTime(String deleteTime) {
            return deleteTime(Output.of(deleteTime));
        }

        /**
         * @param initialEndpointSpec Configuration settings for the initial Read/Write endpoint created inside the initial branch for a newly
         * created project. If omitted, the initial endpoint created will have default settings, without high availability
         * configured. This field does not apply to any endpoints created after project creation. Use
         * spec.default_endpoint_settings to configure default settings for endpoints created after project creation
         * 
         * @return builder
         * 
         */
        public Builder initialEndpointSpec(@Nullable Output<PostgresProjectInitialEndpointSpecArgs> initialEndpointSpec) {
            $.initialEndpointSpec = initialEndpointSpec;
            return this;
        }

        /**
         * @param initialEndpointSpec Configuration settings for the initial Read/Write endpoint created inside the initial branch for a newly
         * created project. If omitted, the initial endpoint created will have default settings, without high availability
         * configured. This field does not apply to any endpoints created after project creation. Use
         * spec.default_endpoint_settings to configure default settings for endpoints created after project creation
         * 
         * @return builder
         * 
         */
        public Builder initialEndpointSpec(PostgresProjectInitialEndpointSpecArgs initialEndpointSpec) {
            return initialEndpointSpec(Output.of(initialEndpointSpec));
        }

        /**
         * @param name (string) - Output only. The full resource path of the project.
         * Format: projects/{project_id}
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name (string) - Output only. The full resource path of the project.
         * Format: projects/{project_id}
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param projectId The part of the name, chosen by the user when the resource was created
         * 
         * @return builder
         * 
         */
        public Builder projectId(@Nullable Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The part of the name, chosen by the user when the resource was created
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param providerConfig Configure the provider for management through account provider.
         * 
         * @return builder
         * 
         */
        public Builder providerConfig(@Nullable Output<PostgresProjectProviderConfigArgs> providerConfig) {
            $.providerConfig = providerConfig;
            return this;
        }

        /**
         * @param providerConfig Configure the provider for management through account provider.
         * 
         * @return builder
         * 
         */
        public Builder providerConfig(PostgresProjectProviderConfigArgs providerConfig) {
            return providerConfig(Output.of(providerConfig));
        }

        /**
         * @param purgeOnDelete If true, permanently deletes the project (hard delete).
         * If false or unset, performs a soft delete
         * 
         * @return builder
         * 
         */
        public Builder purgeOnDelete(@Nullable Output<Boolean> purgeOnDelete) {
            $.purgeOnDelete = purgeOnDelete;
            return this;
        }

        /**
         * @param purgeOnDelete If true, permanently deletes the project (hard delete).
         * If false or unset, performs a soft delete
         * 
         * @return builder
         * 
         */
        public Builder purgeOnDelete(Boolean purgeOnDelete) {
            return purgeOnDelete(Output.of(purgeOnDelete));
        }

        /**
         * @param purgeTime (string) - A timestamp indicating when the project is scheduled for permanent deletion.
         * Empty if the project is not deleted, otherwise set to a timestamp in the future
         * 
         * @return builder
         * 
         */
        public Builder purgeTime(@Nullable Output<String> purgeTime) {
            $.purgeTime = purgeTime;
            return this;
        }

        /**
         * @param purgeTime (string) - A timestamp indicating when the project is scheduled for permanent deletion.
         * Empty if the project is not deleted, otherwise set to a timestamp in the future
         * 
         * @return builder
         * 
         */
        public Builder purgeTime(String purgeTime) {
            return purgeTime(Output.of(purgeTime));
        }

        /**
         * @param spec The spec contains the project configuration, including display_name, pgVersion (Postgres version), history_retention_duration, and default_endpoint_settings
         * 
         * @return builder
         * 
         */
        public Builder spec(@Nullable Output<PostgresProjectSpecArgs> spec) {
            $.spec = spec;
            return this;
        }

        /**
         * @param spec The spec contains the project configuration, including display_name, pgVersion (Postgres version), history_retention_duration, and default_endpoint_settings
         * 
         * @return builder
         * 
         */
        public Builder spec(PostgresProjectSpecArgs spec) {
            return spec(Output.of(spec));
        }

        /**
         * @param status (ProjectStatus) - The current status of a Project
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable Output<PostgresProjectStatusArgs> status) {
            $.status = status;
            return this;
        }

        /**
         * @param status (ProjectStatus) - The current status of a Project
         * 
         * @return builder
         * 
         */
        public Builder status(PostgresProjectStatusArgs status) {
            return status(Output.of(status));
        }

        /**
         * @param uid (string) - System-generated unique ID for the project
         * 
         * @return builder
         * 
         */
        public Builder uid(@Nullable Output<String> uid) {
            $.uid = uid;
            return this;
        }

        /**
         * @param uid (string) - System-generated unique ID for the project
         * 
         * @return builder
         * 
         */
        public Builder uid(String uid) {
            return uid(Output.of(uid));
        }

        /**
         * @param updateTime (string) - A timestamp indicating when the project was last updated
         * 
         * @return builder
         * 
         */
        public Builder updateTime(@Nullable Output<String> updateTime) {
            $.updateTime = updateTime;
            return this;
        }

        /**
         * @param updateTime (string) - A timestamp indicating when the project was last updated
         * 
         * @return builder
         * 
         */
        public Builder updateTime(String updateTime) {
            return updateTime(Output.of(updateTime));
        }

        public PostgresProjectState build() {
            return $;
        }
    }

}
