// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Inputs
{

    public sealed class ModelServingProvisionedThroughputEmailNotificationsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("onUpdateFailures")]
        private InputList<string>? _onUpdateFailures;

        /// <summary>
        /// a list of email addresses to be notified when an endpoint fails to update its configuration or state.
        /// </summary>
        public InputList<string> OnUpdateFailures
        {
            get => _onUpdateFailures ?? (_onUpdateFailures = new InputList<string>());
            set => _onUpdateFailures = value;
        }

        [Input("onUpdateSuccesses")]
        private InputList<string>? _onUpdateSuccesses;

        /// <summary>
        /// a list of email addresses to be notified when an endpoint successfully updates its configuration or state.
        /// </summary>
        public InputList<string> OnUpdateSuccesses
        {
            get => _onUpdateSuccesses ?? (_onUpdateSuccesses = new InputList<string>());
            set => _onUpdateSuccesses = value;
        }

        public ModelServingProvisionedThroughputEmailNotificationsGetArgs()
        {
        }
        public static new ModelServingProvisionedThroughputEmailNotificationsGetArgs Empty => new ModelServingProvisionedThroughputEmailNotificationsGetArgs();
    }
}
