// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * [![Public Beta](https://img.shields.io/badge/Release_Stage-Public_Beta-orange)](https://docs.databricks.com/aws/en/release-notes/release-types)
 *
 * This data source allows you to retrieve tag assignments that have been applied to a particular workspace scoped entity.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as databricks from "@pulumi/databricks";
 *
 * const dashboardTags = databricks.getWorkspaceEntityTagAssignments({
 *     entityType: "dashboards",
 *     entityId: "2807324866692453",
 * });
 * const geniespaceTags = databricks.getWorkspaceEntityTagAssignments({
 *     entityType: "geniespaces",
 *     entityId: "2807324866692453",
 * });
 * ```
 */
export function getWorkspaceEntityTagAssignments(args: GetWorkspaceEntityTagAssignmentsArgs, opts?: pulumi.InvokeOptions): Promise<GetWorkspaceEntityTagAssignmentsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("databricks:index/getWorkspaceEntityTagAssignments:getWorkspaceEntityTagAssignments", {
        "entityId": args.entityId,
        "entityType": args.entityType,
        "pageSize": args.pageSize,
    }, opts);
}

/**
 * A collection of arguments for invoking getWorkspaceEntityTagAssignments.
 */
export interface GetWorkspaceEntityTagAssignmentsArgs {
    /**
     * The identifier of the entity to which the tag is assigned
     */
    entityId: string;
    /**
     * The type of entity to which the tag is assigned. Allowed values are dashboards, geniespaces
     */
    entityType: string;
    /**
     * Optional. Maximum number of tag assignments to return in a single page
     */
    pageSize?: number;
}

/**
 * A collection of values returned by getWorkspaceEntityTagAssignments.
 */
export interface GetWorkspaceEntityTagAssignmentsResult {
    /**
     * (string) - The identifier of the entity to which the tag is assigned
     */
    readonly entityId: string;
    /**
     * (string) - The type of entity to which the tag is assigned. Allowed values are dashboards, geniespaces
     */
    readonly entityType: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly pageSize?: number;
    readonly tagAssignments: outputs.GetWorkspaceEntityTagAssignmentsTagAssignment[];
}
/**
 * [![Public Beta](https://img.shields.io/badge/Release_Stage-Public_Beta-orange)](https://docs.databricks.com/aws/en/release-notes/release-types)
 *
 * This data source allows you to retrieve tag assignments that have been applied to a particular workspace scoped entity.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as databricks from "@pulumi/databricks";
 *
 * const dashboardTags = databricks.getWorkspaceEntityTagAssignments({
 *     entityType: "dashboards",
 *     entityId: "2807324866692453",
 * });
 * const geniespaceTags = databricks.getWorkspaceEntityTagAssignments({
 *     entityType: "geniespaces",
 *     entityId: "2807324866692453",
 * });
 * ```
 */
export function getWorkspaceEntityTagAssignmentsOutput(args: GetWorkspaceEntityTagAssignmentsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetWorkspaceEntityTagAssignmentsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("databricks:index/getWorkspaceEntityTagAssignments:getWorkspaceEntityTagAssignments", {
        "entityId": args.entityId,
        "entityType": args.entityType,
        "pageSize": args.pageSize,
    }, opts);
}

/**
 * A collection of arguments for invoking getWorkspaceEntityTagAssignments.
 */
export interface GetWorkspaceEntityTagAssignmentsOutputArgs {
    /**
     * The identifier of the entity to which the tag is assigned
     */
    entityId: pulumi.Input<string>;
    /**
     * The type of entity to which the tag is assigned. Allowed values are dashboards, geniespaces
     */
    entityType: pulumi.Input<string>;
    /**
     * Optional. Maximum number of tag assignments to return in a single page
     */
    pageSize?: pulumi.Input<number>;
}
